# **Procesamiento de Lenguaje Natural**

## Maestría en Inteligencia Artificial Aplicada
#### Tecnológico de Monterrey
#### Prof Luis Eduardo Falcón Morales

### **Actividad INDIVIDUAL: Sistema inteligente para búsqueda de talento.**

* **Nombre:** Daniel Hidalgo Valdés
* **Matrícula:** A01797852

* ##### **El formato de este cuaderno de Jupyter es libre, pero incluye al menos lo solicitado en el archivo PDF asociado a esta actividad.**

* ##### **Pueden importar los paquetes o librerías que requieran.**

* ##### **Pueden incluir las celdas y líneas de código que deseen.**

# 1. Selección y análisis de la vacante real

## 1.1 Vacante seleccionada

Para esta actividad se seleccionó una vacante real publicada en el portal oficial de empleo de Capital One. La actividad solicita que la vacante elegida incluya empresa, nombre del puesto, descripción, competencias requeridas, responsabilidades y requisitos técnicos, ya que esta información será la entrada principal del sistema inteligente de búsqueda de talento.

**Empresa:** Capital One  
**Nombre de la vacante:** Lead Machine Learning Engineer  
**Área:** Engineering / Machine Learning  
**Ubicaciones:** New York, New York; McLean, Virginia; Plano, Texas  
**Nivel de experiencia:** Manager / Lead  
**Fuente oficial:** Capital One Careers  
**URL de la vacante:** https://www.capitalonecareers.com/job/new-york/lead-machine-learning-engineer/1732/94042209776

**Fecha de publicación:** 16 de abril de 2026  
**Fecha de consulta:** 21 de junio de 2026

## 1.2 Justificación de la elección

Se eligió la vacante de **Lead Machine Learning Engineer** porque representa un caso adecuado para desarrollar un sistema inteligente de búsqueda de talento mediante Procesamiento de Lenguaje Natural. La posición combina conocimientos de machine learning, ingeniería de software, cómputo en la nube, pipelines de datos, MLOps, automatización, validación de modelos, monitoreo en producción e inteligencia artificial responsable.

Esta amplitud técnica permite construir una base de CVs sintéticos con perfiles diversos y evaluar si el sistema es capaz de identificar a los candidatos más adecuados. Además, al tratarse de una vacante de nivel lead, resulta posible diferenciar claramente entre perfiles junior, intermedios y senior, así como entre candidatos altamente alineados, parcialmente alineados y poco alineados con los requisitos del puesto.

## 1.3 Descripción general del puesto

La vacante busca a una persona especializada en Machine Learning Engineering que participe en el diseño técnico, desarrollo e implementación de aplicaciones de aprendizaje automático a escala. El puesto forma parte de un equipo ágil orientado a llevar modelos y sistemas de machine learning a ambientes productivos, asegurando disponibilidad, desempeño, gobernanza y buenas prácticas de desarrollo.

El perfil requiere no solo conocimiento de modelos de machine learning, sino también capacidad para construir soluciones robustas, escalables y mantenibles. Por ello, la vacante se ubica en la intersección entre ciencia de datos, ingeniería de datos, ingeniería de software, arquitectura cloud y MLOps.

## 1.4 Responsabilidades principales

| Área | Responsabilidad |
|---|---|
| Machine Learning | Diseñar, construir y entregar modelos o componentes de machine learning que resuelvan problemas reales de negocio. |
| Infraestructura ML | Tomar decisiones de infraestructura considerando modelos, datos, selección de características, entrenamiento, tuning, dimensionalidad, sesgo, varianza y validación. |
| Desarrollo de software | Escribir, probar y mantener código de aplicación y código asociado a modelos de machine learning. |
| Trabajo colaborativo | Colaborar con equipos ágiles y multifuncionales de producto, ciencia de datos e ingeniería. |
| Producción | Reentrenar, mantener y monitorear modelos en ambientes productivos. |
| Cloud | Utilizar o construir arquitecturas cloud para desplegar modelos optimizados a escala. |
| Pipelines de datos | Construir pipelines de datos optimizados para alimentar modelos de machine learning. |
| CI/CD | Aplicar buenas prácticas de integración continua, despliegue continuo, automatización de pruebas y monitoreo. |
| Gobernanza | Asegurar código bien administrado, reducción de vulnerabilidades, gobernanza de modelos e inteligencia artificial responsable y explicable. |

## 1.5 Competencias técnicas requeridas

| Competencia | Descripción |
|---|---|
| Machine Learning Engineering | Construcción, escalamiento y optimización de sistemas de machine learning. |
| Programación | Experiencia con Python, Scala o Java. |
| Sistemas distribuidos | Diseño y construcción de soluciones intensivas en datos mediante cómputo distribuido. |
| MLOps | Despliegue, monitoreo, mantenimiento y reentrenamiento de modelos en producción. |
| Pipelines de datos | Construcción de pipelines productivos para alimentar modelos de ML. |
| Cloud Computing | Experiencia con plataformas como AWS, Azure o Google Cloud Platform. |
| Frameworks de ML | Uso de herramientas como scikit-learn, PyTorch, Dask, Spark o TensorFlow. |
| CI/CD | Automatización de pruebas, despliegues y monitoreo. |
| Responsible AI | Buenas prácticas de inteligencia artificial responsable, explicable y gobernada. |

## 1.6 Requisitos mínimos

| Requisito | Detalle |
|---|---|
| Escolaridad | Licenciatura. |
| Experiencia en datos | Al menos 6 años diseñando y construyendo soluciones intensivas en datos mediante cómputo distribuido. |
| Programación | Al menos 4 años programando con Python, Scala o Java. |
| Sistemas de ML | Al menos 2 años construyendo, escalando y optimizando sistemas de machine learning. |

## 1.7 Requisitos deseables

| Requisito deseable | Detalle |
|---|---|
| Posgrado | Maestría o doctorado en ciencias de la computación, ingeniería eléctrica, matemáticas o campo similar. |
| Pipelines productivos | Más de 3 años construyendo pipelines de datos listos para producción. |
| Frameworks de ML | Más de 3 años usando frameworks reconocidos como scikit-learn, PyTorch, Dask, Spark o TensorFlow. |
| Código mantenible | Más de 2 años desarrollando código eficiente, resiliente y mantenible. |
| Preparación de datos | Más de 2 años recolectando y preparando datos para modelos de machine learning. |
| Liderazgo | Experiencia liderando personas o equipos de soluciones ML. |
| Cloud | Experiencia desplegando soluciones en AWS, Azure o Google Cloud Platform. |
| Impacto profesional | Participación en conferencias, publicaciones, blogs, open source o patentes. |

## 1.8 Síntesis del perfil ideal

Para efectos del sistema inteligente, la vacante puede sintetizarse de la siguiente manera:

> Se busca un perfil senior o lead de Machine Learning Engineering, con experiencia sólida en diseño, construcción, despliegue y monitoreo de sistemas de machine learning en producción. Debe dominar programación en Python, Scala o Java; contar con experiencia en sistemas distribuidos, pipelines de datos, cloud computing, frameworks de machine learning, CI/CD, MLOps, gobernanza de modelos e inteligencia artificial responsable. Se valoran habilidades de liderazgo técnico, colaboración con equipos ágiles y capacidad para construir soluciones escalables orientadas a problemas reales de negocio.

Esta síntesis funcionará como la consulta principal contra la cual se compararán los CVs sintéticos generados en la actividad.

In [100]:
# Se crea un diccionario llamado "vacante" para guardar la información principal
# de la vacante real seleccionada. Esta información será usada más adelante
# como entrada del sistema de búsqueda semántica.

vacante = {

    # Información general de la empresa y del puesto seleccionado.
    "empresa": "Capital One",
    "puesto": "Lead Machine Learning Engineer",
    "area": "Engineering / Machine Learning",

    # Ubicaciones publicadas en la vacante oficial.
    "ubicaciones": ["New York, NY", "McLean, VA", "Plano, TX"],

    # Fuente oficial de donde se tomó la vacante.
    "fuente": "Capital One Careers",
    "url": "https://www.capitalonecareers.com/job/new-york/lead-machine-learning-engineer/1732/94042209776",

    # Descripción resumida del perfil ideal.
    # Esta síntesis funcionará como consulta principal para comparar los CVs.
    "descripcion_sintetica": """
    Se busca un perfil senior o lead de Machine Learning Engineering, con experiencia sólida
    en diseño, construcción, despliegue y monitoreo de sistemas de machine learning en producción.
    Debe dominar programación en Python, Scala o Java; contar con experiencia en sistemas
    distribuidos, pipelines de datos, cloud computing, frameworks de machine learning, CI/CD,
    MLOps, gobernanza de modelos e inteligencia artificial responsable. Se valoran habilidades
    de liderazgo técnico, colaboración con equipos ágiles y capacidad para construir soluciones
    escalables orientadas a problemas reales de negocio.
    """,

    # Lista de competencias clave extraídas de la vacante.
    # Estas competencias se usarán después para enriquecer la consulta semántica.
    "competencias_clave": [
        "Machine Learning Engineering",
        "Python",
        "Scala",
        "Java",
        "Sistemas distribuidos",
        "Pipelines de datos",
        "MLOps",
        "Cloud Computing",
        "AWS",
        "Azure",
        "Google Cloud Platform",
        "scikit-learn",
        "PyTorch",
        "Dask",
        "Spark",
        "TensorFlow",
        "CI/CD",
        "Responsible AI",
        "Explainable AI",
        "Liderazgo técnico"
    ]
}

vacante

{'empresa': 'Capital One',
 'puesto': 'Lead Machine Learning Engineer',
 'area': 'Engineering / Machine Learning',
 'ubicaciones': ['New York, NY', 'McLean, VA', 'Plano, TX'],
 'fuente': 'Capital One Careers',
 'url': 'https://www.capitalonecareers.com/job/new-york/lead-machine-learning-engineer/1732/94042209776',
 'descripcion_sintetica': '\n    Se busca un perfil senior o lead de Machine Learning Engineering, con experiencia sólida\n    en diseño, construcción, despliegue y monitoreo de sistemas de machine learning en producción.\n    Debe dominar programación en Python, Scala o Java; contar con experiencia en sistemas\n    distribuidos, pipelines de datos, cloud computing, frameworks de machine learning, CI/CD,\n    MLOps, gobernanza de modelos e inteligencia artificial responsable. Se valoran habilidades\n    de liderazgo técnico, colaboración con equipos ágiles y capacidad para construir soluciones\n    escalables orientadas a problemas reales de negocio.\n    ',
 'competencias_clave': ['Machine Learning Engineering',
  'Python',
  'Scala',
  'Java',
  'Sistemas distribuidos',
  'Pipelines de datos',
  'MLOps',
  'Cloud Computing',
  'AWS',
  'Azure',
  'Google Cloud Platform',
  'scikit-learn',
  'PyTorch',
  'Dask',
  'Spark',
  'TensorFlow',
  'CI/CD',
  'Responsible AI',
  'Explainable AI',
  'Liderazgo técnico']}

## 1.9 Matriz de requisitos de la vacante

A partir de la vacante seleccionada, se construyó una matriz de requisitos para identificar los elementos que el sistema deberá buscar en los CVs sintéticos. Esta matriz permite transformar la descripción general del puesto en criterios observables de evaluación, como experiencia, habilidades técnicas, herramientas, liderazgo, MLOps, cloud computing y buenas prácticas de inteligencia artificial responsable.

La matriz será utilizada posteriormente como referencia para la búsqueda semántica, el ranking de candidatos y la justificación del Top 5 recomendado por el sistema.

In [101]:
import pandas as pd

# Se construye una lista de diccionarios con los requisitos principales de la vacante.
# Cada diccionario representa un criterio que el sistema deberá considerar
# al comparar los CVs sintéticos contra la vacante.

requisitos_vacante = [
    {
        "dimension": "Experiencia",
        "requisito": "6 o más años diseñando y construyendo soluciones intensivas en datos",
        "tipo": "Mínimo",
        "peso": 5
    },
    {
        "dimension": "Programación",
        "requisito": "Experiencia sólida programando en Python, Scala o Java",
        "tipo": "Mínimo",
        "peso": 5
    },
    {
        "dimension": "Machine Learning",
        "requisito": "Experiencia construyendo, escalando y optimizando sistemas de machine learning",
        "tipo": "Mínimo",
        "peso": 5
    },
    {
        "dimension": "MLOps",
        "requisito": "Despliegue, monitoreo, mantenimiento y reentrenamiento de modelos en producción",
        "tipo": "Clave",
        "peso": 5
    },
    {
        "dimension": "Cloud Computing",
        "requisito": "Experiencia con AWS, Azure o Google Cloud Platform",
        "tipo": "Clave",
        "peso": 4
    },
    {
        "dimension": "Pipelines de datos",
        "requisito": "Construcción de pipelines productivos para alimentar modelos de machine learning",
        "tipo": "Clave",
        "peso": 4
    },
    {
        "dimension": "Frameworks de ML",
        "requisito": "Uso de scikit-learn, PyTorch, TensorFlow, Spark o Dask",
        "tipo": "Clave",
        "peso": 4
    },
    {
        "dimension": "CI/CD",
        "requisito": "Automatización de pruebas, integración continua y despliegue continuo",
        "tipo": "Deseable",
        "peso": 3
    },
    {
        "dimension": "Responsible AI",
        "requisito": "Conocimiento de inteligencia artificial responsable, explicable y gobernanza de modelos",
        "tipo": "Deseable",
        "peso": 3
    },
    {
        "dimension": "Liderazgo técnico",
        "requisito": "Capacidad para liderar soluciones, orientar equipos y colaborar en contextos ágiles",
        "tipo": "Deseable",
        "peso": 3
    }
]

df_requisitos = pd.DataFrame(requisitos_vacante)

df_requisitos.head(10)

,dimension,requisito,tipo,peso
0,Experiencia,6 o más años diseñando y construyendo solucion...,Mínimo,5
1,Programación,"Experiencia sólida programando en Python, Scal...",Mínimo,5
2,Machine Learning,"Experiencia construyendo, escalando y optimiza...",Mínimo,5
3,MLOps,"Despliegue, monitoreo, mantenimiento y reentre...",Clave,5
4,Cloud Computing,"Experiencia con AWS, Azure o Google Cloud Plat...",Clave,4
5,Pipelines de datos,Construcción de pipelines productivos para ali...,Clave,4
6,Frameworks de ML,"Uso de scikit-learn, PyTorch, TensorFlow, Spar...",Clave,4
7,CI/CD,"Automatización de pruebas, integración continu...",Deseable,3
8,Responsible AI,Conocimiento de inteligencia artificial respon...,Deseable,3
9,Liderazgo técnico,"Capacidad para liderar soluciones, orientar eq...",Deseable,3

# 2. Diseño de la base de CVs sintéticos

Antes de generar los CVs sintéticos, se definió una estructura general para asegurar diversidad, coherencia y utilidad dentro del sistema de búsqueda de talento. La base estará compuesta por 20 CVs sintéticos, distribuidos en tres niveles de experiencia: Junior, Intermedio/Semi-Senior y Senior.

Esta distribución permite evaluar si el sistema inteligente distingue adecuadamente entre perfiles altamente alineados con la vacante, perfiles parcialmente relacionados y perfiles menos adecuados. Además, se definieron seis tipos de perfiles profesionales para evitar que la información quede demasiado dispersa, pero manteniendo variedad suficiente para probar el comportamiento de la búsqueda semántica.

## 2.1 Niveles de experiencia
El contenido completo de cada CV se desarrolla posteriormente en la sección 6, donde se construyen y exportan los documentos individuales en los formatos definidos.

| Nivel                    | Cantidad | Descripción                                                                                                                                                                                                                                             |
| ------------------------ | -------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Junior                   |        5 | Perfiles con experiencia inicial, generalmente entre 0 y 2 años. Pueden tener proyectos académicos, prácticas profesionales o experiencia limitada en herramientas de datos, programación o machine learning.                                           |
| Intermedio / Semi-Senior |       10 | Perfiles con experiencia profesional consolidada, generalmente entre 3 y 5 años. Pueden participar en proyectos productivos, pipelines de datos, modelos de machine learning, análisis de datos o desarrollo de software.                               |
| Senior                   |        5 | Perfiles con experiencia avanzada, generalmente 6 años o más. Pueden liderar soluciones técnicas, diseñar arquitecturas, desplegar modelos en producción, trabajar con cloud, MLOps, sistemas distribuidos y colaborar con equipos multidisciplinarios. |

## 2.2 Tipos de perfiles definidos

Los perfiles sintéticos se agruparán en seis categorías profesionales:

| Tipo de perfil            | Relación con la vacante                                                                                                                          |
| ------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------ |
| Machine Learning Engineer | Muy alta relación con la vacante, por su experiencia en modelos, despliegue, MLOps y sistemas productivos.                                       |
| Data Scientist            | Alta relación, especialmente si tiene experiencia en modelos predictivos, validación, Python y herramientas de ML.                               |
| Data Engineer             | Relación alta o media, por su experiencia en pipelines, datos, cloud y sistemas distribuidos.                                                    |
| MLOps Engineer            | Muy alta relación, por su experiencia en monitoreo, despliegue, CI/CD, cloud y mantenimiento de modelos.                                         |
| BI Analyst                | Relación media o baja, útil para validar si el sistema distingue perfiles de análisis de datos que no necesariamente cumplen con ML Engineering. |
| Software Engineer         | Relación variable, dependiendo de su experiencia en backend, cloud, APIs, sistemas distribuidos o integración de modelos.                        |

## 2.3 Criterio de diversidad

La base de CVs incluirá candidatos cercanos y no tan cercanos a la vacante. Esto es importante porque el sistema no solo debe recuperar perfiles similares, sino también jerarquizarlos adecuadamente. Si todos los candidatos fueran igualmente buenos, no sería posible evaluar si la búsqueda semántica y el ranking funcionan correctamente.

Por ello, se incluirán perfiles altamente alineados, como Machine Learning Engineer y MLOps Engineer; perfiles relacionados, como Data Scientist y Data Engineer; y perfiles parcialmente relacionados, como BI Analyst o Software Engineer sin experiencia profunda en machine learning.

## 2.4 Formatos de los documentos

Para construir una base de conocimiento multimodal, los CVs se guardarán en dos formatos:

| Formato | Cantidad |
| ------- | -------: |
| PDF     |       16 |
| PNG     |        4 |

La distribución de los archivos PNG será la siguiente:

| Nivel                    | Cantidad de PNG |
| ------------------------ | --------------: |
| Junior                   |               1 |
| Intermedio / Semi-Senior |               2 |
| Senior                   |               1 |

El resto de los CVs se guardará en formato PDF. Esta decisión permite probar que el sistema puede trabajar con información proveniente tanto de documentos de texto como de imágenes.

In [102]:
diseno_cvs = [

    # Perfiles Junior: deben ser 5 candidatos.
    {"id": "CAND-001", "nivel": "Junior", "perfil": "Data Scientist", "experiencia_anios": 1, "formato": "PNG", "alineacion_esperada": "Media"},
    {"id": "CAND-002", "nivel": "Junior", "perfil": "Machine Learning Engineer", "experiencia_anios": 2, "formato": "PDF", "alineacion_esperada": "Media"},
    {"id": "CAND-003", "nivel": "Junior", "perfil": "BI Analyst", "experiencia_anios": 1, "formato": "PDF", "alineacion_esperada": "Baja"},
    {"id": "CAND-004", "nivel": "Junior", "perfil": "Software Engineer", "experiencia_anios": 2, "formato": "PDF", "alineacion_esperada": "Media"},
    {"id": "CAND-005", "nivel": "Junior", "perfil": "Data Engineer", "experiencia_anios": 2, "formato": "PDF", "alineacion_esperada": "Media"},

    # Perfiles Intermedio o Semi-Senior: deben ser 10 candidatos.
    {"id": "CAND-006", "nivel": "Intermedio", "perfil": "Machine Learning Engineer", "experiencia_anios": 4, "formato": "PNG", "alineacion_esperada": "Alta"},
    {"id": "CAND-007", "nivel": "Intermedio", "perfil": "Data Scientist", "experiencia_anios": 5, "formato": "PDF", "alineacion_esperada": "Alta"},
    {"id": "CAND-008", "nivel": "Intermedio", "perfil": "Data Engineer", "experiencia_anios": 4, "formato": "PDF", "alineacion_esperada": "Media-Alta"},
    {"id": "CAND-009", "nivel": "Intermedio", "perfil": "MLOps Engineer", "experiencia_anios": 5, "formato": "PNG", "alineacion_esperada": "Alta"},
    {"id": "CAND-010", "nivel": "Intermedio", "perfil": "BI Analyst", "experiencia_anios": 4, "formato": "PDF", "alineacion_esperada": "Media-Baja"},
    {"id": "CAND-011", "nivel": "Intermedio", "perfil": "Software Engineer", "experiencia_anios": 5, "formato": "PDF", "alineacion_esperada": "Media"},
    {"id": "CAND-012", "nivel": "Intermedio", "perfil": "Machine Learning Engineer", "experiencia_anios": 5, "formato": "PDF", "alineacion_esperada": "Alta"},
    {"id": "CAND-013", "nivel": "Intermedio", "perfil": "Data Scientist", "experiencia_anios": 3, "formato": "PDF", "alineacion_esperada": "Media-Alta"},
    {"id": "CAND-014", "nivel": "Intermedio", "perfil": "Data Engineer", "experiencia_anios": 5, "formato": "PDF", "alineacion_esperada": "Media-Alta"},
    {"id": "CAND-015", "nivel": "Intermedio", "perfil": "Software Engineer", "experiencia_anios": 4, "formato": "PDF", "alineacion_esperada": "Media"},

    # Perfiles Senior: deben ser 5 candidatos.
    {"id": "CAND-016", "nivel": "Senior", "perfil": "Lead Machine Learning Engineer", "experiencia_anios": 8, "formato": "PNG", "alineacion_esperada": "Muy alta"},
    {"id": "CAND-017", "nivel": "Senior", "perfil": "MLOps Engineer", "experiencia_anios": 7, "formato": "PDF", "alineacion_esperada": "Muy alta"},
    {"id": "CAND-018", "nivel": "Senior", "perfil": "Data Architect", "experiencia_anios": 9, "formato": "PDF", "alineacion_esperada": "Alta"},
    {"id": "CAND-019", "nivel": "Senior", "perfil": "Data Scientist", "experiencia_anios": 7, "formato": "PDF", "alineacion_esperada": "Alta"},
    {"id": "CAND-020", "nivel": "Senior", "perfil": "Software Architect", "experiencia_anios": 10, "formato": "PDF", "alineacion_esperada": "Media-Alta"}
]
# Se convierte la lista de diccionarios en un DataFrame.
df_diseno_cvs = pd.DataFrame(diseno_cvs)

# Se muestran los 20 registros para verificar que todos los candidatos
df_diseno_cvs.head(20)

,id,nivel,perfil,experiencia_anios,formato,alineacion_esperada
0,CAND-001,Junior,Data Scientist,1,PNG,Media
1,CAND-002,Junior,Machine Learning Engineer,2,PDF,Media
2,CAND-003,Junior,BI Analyst,1,PDF,Baja
3,CAND-004,Junior,Software Engineer,2,PDF,Media
4,CAND-005,Junior,Data Engineer,2,PDF,Media
5,CAND-006,Intermedio,Machine Learning Engineer,4,PNG,Alta
6,CAND-007,Intermedio,Data Scientist,5,PDF,Alta
7,CAND-008,Intermedio,Data Engineer,4,PDF,Media-Alta
8,CAND-009,Intermedio,MLOps Engineer,5,PNG,Alta
9,CAND-010,Intermedio,BI Analyst,4,PDF,Media-Baja
10,CAND-011,Intermedio,Software Engineer,5,PDF,Media
11,CAND-012,Intermedio,Machine Learning Engineer,5,PDF,Alta
12,CAND-013,Intermedio,Data Scientist,3,PDF,Media-Alta
13,CAND-014,Intermedio,Data Engineer,5,PDF,Media-Alta
14,CAND-015,Intermedio,Software Engineer,4,PDF,Media
15,CAND-016,Senior,Lead Machine Learning Engineer,8,PNG,Muy alta
16,CAND-017,Senior,MLOps Engineer,7,PDF,Muy alta
17,CAND-018,Senior,Data Architect,9,PDF,Alta
18,CAND-019,Senior,Data Scientist,7,PDF,Alta
19,CAND-020,Senior,Software Architect,10,PDF,Media-Alta

In [103]:
# Se verifica la distribución de los CVs sintéticos por nivel de experiencia.
resumen_niveles = df_diseno_cvs["nivel"].value_counts()

# Se verifica la distribución de formatos de archivo.
resumen_formatos = df_diseno_cvs["formato"].value_counts()

# Se filtran únicamente los CVs en formato PNG y se cuenta cuántos hay por nivel.
resumen_png_por_nivel = df_diseno_cvs[df_diseno_cvs["formato"] == "PNG"]["nivel"].value_counts()

print("Distribución por nivel:")
display(resumen_niveles)

print("\nDistribución por formato:")
display(resumen_formatos)

print("\nDistribución de PNG por nivel:")
display(resumen_png_por_nivel)

Distribución por nivel:

nivel
Intermedio    10
Junior         5
Senior         5
Name: count, dtype: int64

Distribución por formato:

formato
PDF    16
PNG     4
Name: count, dtype: int64

Distribución de PNG por nivel:

nivel
Intermedio    2
Junior        1
Senior        1
Name: count, dtype: int64

## 2.5 Verificación de la distribución de CVs

La distribución definida cumple con la cantidad solicitada para la actividad: 5 perfiles Junior, 10 perfiles Intermedio/Semi-Senior y 5 perfiles Senior. Además, se definió una variedad controlada de perfiles profesionales relacionados con ciencia de datos, machine learning, ingeniería de datos, MLOps, business intelligence y desarrollo de software.

Esta planeación permitirá generar una base de conocimiento suficientemente diversa para probar el comportamiento del sistema inteligente. Algunos perfiles estarán altamente alineados con la vacante seleccionada, mientras que otros estarán solo parcialmente relacionados. Esto permitirá evaluar si la búsqueda semántica y el ranking final logran distinguir entre candidatos fuertes, candidatos aceptables y candidatos menos adecuados para el puesto.

# 3. Consideraciones éticas y anonimización de los CVs sintéticos

La actividad requiere generar 20 CVs sintéticos con inteligencia artificial para construir la base de conocimiento del sistema. Sin embargo, estos CVs no deben incluir datos personales sensibles ni información que permita identificar directa o indirectamente a una persona real.

Por esa razón, en esta propuesta se decidió utilizar identificadores anónimos para cada candidato, por ejemplo: `CAND-001`, `CAND-002`, `CAND-003`, etc. De esta manera, el sistema puede analizar formación, experiencia, habilidades técnicas, habilidades blandas, certificaciones, idiomas y proyectos relevantes sin depender de información personal.

## 3.1 Datos excluidos deliberadamente

En los CVs sintéticos no se incluirán los siguientes elementos:

| Dato excluido | Razón ética |
|---|---|
| Nombre de la persona | Puede generar sesgos asociados a origen social, género, cultura o familiaridad. |
| Fotografía | Puede inducir sesgos por apariencia, edad percibida, género, etnicidad o discapacidad visible. |
| Género | No es necesario para evaluar competencias profesionales y puede provocar discriminación. |
| Edad | Puede inducir sesgos por juventud o seniority percibido, independientemente de la experiencia real. |
| Nacionalidad | Puede generar sesgos culturales o migratorios no relacionados con el desempeño profesional. |
| Estado civil | No tiene relevancia técnica para el puesto y puede generar discriminación. |
| Dirección personal | No aporta valor al análisis semántico y compromete privacidad. |
| Teléfono o correo real | No es necesario para la actividad y podría confundirse con información de contacto real. |

## 3.2 Importancia de la anonimización

La anonimización permite que el sistema se concentre en los elementos realmente relevantes para la selección de talento: experiencia profesional, competencias técnicas, nivel de dominio, certificaciones, proyectos, herramientas utilizadas y habilidades de colaboración. Esto reduce el riesgo de que el modelo o el evaluador humano tomen decisiones basadas en atributos personales que no deberían influir en la recomendación.

Además, al usar CVs sintéticos y anónimos, se protege la privacidad de personas reales y se evita exponer datos personales en una actividad académica. Este enfoque es coherente con el propósito del sistema: apoyar el análisis inicial de candidatos sin reemplazar al reclutador ni eliminar la supervisión humana.

## 3.3 Criterio adoptado para esta actividad

Para esta actividad, cada CV será identificado únicamente mediante un código anónimo. La información incluida se limitará a:

- Resumen profesional.
- Formación académica.
- Experiencia laboral.
- Habilidades técnicas.
- Habilidades blandas.
- Certificaciones.
- Idiomas.
- Proyectos relevantes.

Con esto se busca construir una base de conocimiento útil para la búsqueda semántica, pero sin introducir datos personales innecesarios ni variables que puedan favorecer decisiones sesgadas.

In [104]:
politica_anonimizacion = {
    # Identificador anónimo que reemplaza cualquier nombre real.
    # Esto evita asociar los perfiles con personas reales.
    "identificador": "Cada candidato será identificado como CAND-001, CAND-002, etc.",
    "datos_excluidos": [
        "Nombre real",
        "Fotografía",
        "Género",
        "Edad",
        "Nacionalidad",
        "Estado civil",
        "Dirección personal",
        "Teléfono",
        "Correo electrónico real"
    ],

    # Lista de datos personales o sensibles que se excluyen deliberadamente.
    "datos_permitidos": [
        "Resumen profesional",
        "Formación académica",
        "Experiencia laboral",
        "Habilidades técnicas",
        "Habilidades blandas",
        "Certificaciones",
        "Idiomas",
        "Proyectos relevantes"
    ],

    # Lista de datos profesionales que sí se pueden usar
    "objetivo": """
    Reducir riesgos de sesgo y proteger la privacidad, permitiendo que el sistema evalúe
    únicamente información profesional relevante para la vacante.
    """
}

politica_anonimizacion

{'identificador': 'Cada candidato será identificado como CAND-001, CAND-002, etc.',
 'datos_excluidos': ['Nombre real',
  'Fotografía',
  'Género',
  'Edad',
  'Nacionalidad',
  'Estado civil',
  'Dirección personal',
  'Teléfono',
  'Correo electrónico real'],
 'datos_permitidos': ['Resumen profesional',
  'Formación académica',
  'Experiencia laboral',
  'Habilidades técnicas',
  'Habilidades blandas',
  'Certificaciones',
  'Idiomas',
  'Proyectos relevantes'],
 'objetivo': '\n    Reducir riesgos de sesgo y proteger la privacidad, permitiendo que el sistema evalúe\n    únicamente información profesional relevante para la vacante.\n    '}

# 4. Prompt utilizado para generar los CVs sintéticos y descripción de niveles

Para generar los CVs sintéticos se utilizó un prompt orientado a producir perfiles profesionales variados, anónimos y coherentes con la vacante seleccionada. El objetivo fue construir una base de conocimiento útil para evaluar un sistema inteligente de búsqueda de talento, sin utilizar información de personas reales.

El prompt solicitó generar candidatos distribuidos en tres niveles de experiencia: Junior, Intermedio/Semi-Senior y Senior. Esta distribución permite observar si el sistema distingue entre perfiles iniciales, perfiles con experiencia consolidada y perfiles avanzados o de liderazgo técnico.

## 4.1 Descripción de los niveles utilizados

| Nivel                    | Cantidad | Criterio utilizado                                                                                                                                                                            |
| ------------------------ | -------: | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Junior                   |        5 | Perfiles con experiencia inicial, entre 0 y 2 años, con conocimientos básicos o proyectos iniciales en datos, programación o machine learning.                                                |
| Intermedio / Semi-Senior |       10 | Perfiles con experiencia de 3 a 5 años, capaces de participar en proyectos productivos, pipelines, modelos, análisis de datos o desarrollo de software.                                       |
| Senior                   |        5 | Perfiles con 6 años o más de experiencia, capaces de liderar soluciones técnicas, diseñar arquitecturas, desplegar modelos en producción y trabajar con MLOps, cloud o sistemas distribuidos. |

## 4.2 Modelo utilizado

El LLM utilizado para generar los CVs sintéticos fue ChatGPT. A partir del prompt documentado en esta sección, se generaron perfiles sintéticos anónimos, variados y coherentes con la vacante seleccionada.

## 4.3 Prompt utilizado

El siguiente prompt fue utilizado como base para generar los 20 CVs sintéticos:

> Actúa como especialista en reclutamiento tecnológico y generación de datos sintéticos. Necesito generar 20 CVs sintéticos para una actividad académica de Procesamiento de Lenguaje Natural.
>
> La vacante objetivo es Lead Machine Learning Engineer en Capital One. El perfil ideal requiere experiencia en machine learning engineering, Python, Scala o Java, sistemas distribuidos, pipelines de datos, MLOps, cloud computing, AWS, Azure o Google Cloud Platform, frameworks como scikit-learn, PyTorch, TensorFlow, Spark o Dask, CI/CD, monitoreo de modelos, gobernanza de modelos, responsible AI, explainable AI y liderazgo técnico.
>
> Genera 20 CVs sintéticos, sin nombres reales, sin fotografía, sin género, sin edad, sin nacionalidad, sin estado civil, sin dirección, sin teléfono y sin correo electrónico real. Cada candidato debe identificarse únicamente con un código anónimo: CAND-001, CAND-002, etc.
>
> Los CVs deben distribuirse así: 5 Junior, 10 Intermedio/Semi-Senior y 5 Senior.
>
> Incluye perfiles variados, pero relacionados con la vacante: Machine Learning Engineer, Data Scientist, Data Engineer, MLOps Engineer, BI Analyst y Software Engineer o Software Architect. Algunos perfiles deben estar altamente alineados con la vacante, otros parcialmente alineados y otros menos alineados, para poder evaluar posteriormente el desempeño del sistema de búsqueda semántica.
>
> Cada CV debe incluir las siguientes secciones: resumen profesional, formación académica, experiencia laboral, habilidades técnicas, habilidades blandas, certificaciones, idiomas y proyectos relevantes.
>
> Redacta los CVs en español, con estilo profesional, realista y sintético. Evita información personal sensible o identificable. Mantén coherencia entre el nivel de experiencia, los años de experiencia, las habilidades técnicas y los proyectos relevantes.

In [105]:
# Se guarda en una variable de texto el prompt utilizado para generar los CVs sintéticos.
prompt_generacion_cvs = """
Actúa como especialista en reclutamiento tecnológico y generación de datos sintéticos.
Necesito generar 20 CVs sintéticos para una actividad académica de Procesamiento de Lenguaje Natural.

La vacante objetivo es Lead Machine Learning Engineer en Capital One. El perfil ideal requiere experiencia
en machine learning engineering, Python, Scala o Java, sistemas distribuidos, pipelines de datos, MLOps,
cloud computing, AWS, Azure o Google Cloud Platform, frameworks como scikit-learn, PyTorch, TensorFlow,
Spark o Dask, CI/CD, monitoreo de modelos, gobernanza de modelos, responsible AI, explainable AI y liderazgo técnico.

Genera 20 CVs sintéticos, sin nombres reales, sin fotografía, sin género, sin edad, sin nacionalidad,
sin estado civil, sin dirección, sin teléfono y sin correo electrónico real. Cada candidato debe identificarse
únicamente con un código anónimo: CAND-001, CAND-002, etc.

Los CVs deben distribuirse así: 5 Junior, 10 Intermedio/Semi-Senior y 5 Senior.

Incluye perfiles variados, pero relacionados con la vacante: Machine Learning Engineer, Data Scientist,
Data Engineer, MLOps Engineer, BI Analyst y Software Engineer o Software Architect. Algunos perfiles deben estar
altamente alineados con la vacante, otros parcialmente alineados y otros menos alineados, para poder evaluar
posteriormente el desempeño del sistema de búsqueda semántica.

Cada CV debe incluir las siguientes secciones: resumen profesional, formación académica, experiencia laboral,
habilidades técnicas, habilidades blandas, certificaciones, idiomas y proyectos relevantes.

Redacta los CVs en español, con estilo profesional, realista y sintético. Evita información personal sensible
o identificable. Mantén coherencia entre el nivel de experiencia, los años de experiencia, las habilidades técnicas
y los proyectos relevantes.
"""

print(prompt_generacion_cvs)

Actúa como especialista en reclutamiento tecnológico y generación de datos sintéticos.
Necesito generar 20 CVs sintéticos para una actividad académica de Procesamiento de Lenguaje Natural.

La vacante objetivo es Lead Machine Learning Engineer en Capital One. El perfil ideal requiere experiencia
en machine learning engineering, Python, Scala o Java, sistemas distribuidos, pipelines de datos, MLOps,
cloud computing, AWS, Azure o Google Cloud Platform, frameworks como scikit-learn, PyTorch, TensorFlow,
Spark o Dask, CI/CD, monitoreo de modelos, gobernanza de modelos, responsible AI, explainable AI y liderazgo técnico.

Genera 20 CVs sintéticos, sin nombres reales, sin fotografía, sin género, sin edad, sin nacionalidad,
sin estado civil, sin dirección, sin teléfono y sin correo electrónico real. Cada candidato debe identificarse
únicamente con un código anónimo: CAND-001, CAND-002, etc.

Los CVs deben distribuirse así: 5 Junior, 10 Intermedio/Semi-Senior y 5 Senior.

Incluye perfiles variados, pero relacionados con la vacante: Machine Learning Engineer, Data Scientist,
Data Engineer, MLOps Engineer, BI Analyst y Software Engineer o Software Architect. Algunos perfiles deben estar
altamente alineados con la vacante, otros parcialmente alineados y otros menos alineados, para poder evaluar
posteriormente el desempeño del sistema de búsqueda semántica.

Cada CV debe incluir las siguientes secciones: resumen profesional, formación académica, experiencia laboral,
habilidades técnicas, habilidades blandas, certificaciones, idiomas y proyectos relevantes.

Redacta los CVs en español, con estilo profesional, realista y sintético. Evita información personal sensible
o identificable. Mantén coherencia entre el nivel de experiencia, los años de experiencia, las habilidades técnicas
y los proyectos relevantes.

# 5. Tipos de perfiles generados

A partir del diseño de la base de CVs sintéticos, se generaron perfiles variados relacionados en distinto grado con la vacante de Lead Machine Learning Engineer. Aunque algunos candidatos tienen denominaciones más específicas, como Lead Machine Learning Engineer, Data Architect o Software Architect, para el análisis general se agruparon dentro de seis categorías principales.

Esta agrupación permite mantener una diversidad controlada y evita que la base de conocimiento quede demasiado dispersa. El objetivo es contar con perfiles altamente alineados con la vacante, perfiles relacionados y perfiles parcialmente relacionados, para evaluar posteriormente si el sistema de búsqueda semántica logra jerarquizar adecuadamente a los mejores candidatos.

In [106]:
# Agrupación de perfiles específicos en las seis categorías principales
df_diseno_cvs["categoria_perfil"] = df_diseno_cvs["perfil"].replace({
    "Lead Machine Learning Engineer": "Machine Learning Engineer",
    "Data Architect": "Data Engineer",
    "Software Architect": "Software Engineer"
})


# Se construye una tabla resumen para contar cuántos candidatos hay en cada categoría principal de perfil
df_tipos_perfil = (
    df_diseno_cvs
    .groupby("categoria_perfil")
    .agg(
        cantidad=("id", "count"),
        candidatos=("id", lambda x: ", ".join(x)),
        niveles=("nivel", lambda x: ", ".join(sorted(x.unique()))),
        formatos=("formato", lambda x: ", ".join(sorted(x.unique())))
    )
    .reset_index()
    .sort_values("cantidad", ascending=False)
)

df_tipos_perfil

,categoria_perfil,cantidad,candidatos,niveles,formatos
1,Data Engineer,4,"CAND-005, CAND-008, CAND-014, CAND-018","Intermedio, Junior, Senior",PDF
2,Data Scientist,4,"CAND-001, CAND-007, CAND-013, CAND-019","Intermedio, Junior, Senior","PDF, PNG"
5,Software Engineer,4,"CAND-004, CAND-011, CAND-015, CAND-020","Intermedio, Junior, Senior",PDF
4,Machine Learning Engineer,4,"CAND-002, CAND-006, CAND-012, CAND-016","Intermedio, Junior, Senior","PDF, PNG"
0,BI Analyst,2,"CAND-003, CAND-010","Intermedio, Junior",PDF
3,MLOps Engineer,2,"CAND-009, CAND-017","Intermedio, Senior","PDF, PNG"

In [107]:
# Se verifica cuántas categorías principales de perfiles profesionales se generaron.
print("Total de categorías principales:", df_tipos_perfil["categoria_perfil"].nunique())
print("Total de CVs sintéticos:", df_tipos_perfil["cantidad"].sum())

display(df_tipos_perfil)

Total de categorías principales: 6
Total de CVs sintéticos: 20

,categoria_perfil,cantidad,candidatos,niveles,formatos
1,Data Engineer,4,"CAND-005, CAND-008, CAND-014, CAND-018","Intermedio, Junior, Senior",PDF
2,Data Scientist,4,"CAND-001, CAND-007, CAND-013, CAND-019","Intermedio, Junior, Senior","PDF, PNG"
5,Software Engineer,4,"CAND-004, CAND-011, CAND-015, CAND-020","Intermedio, Junior, Senior",PDF
4,Machine Learning Engineer,4,"CAND-002, CAND-006, CAND-012, CAND-016","Intermedio, Junior, Senior","PDF, PNG"
0,BI Analyst,2,"CAND-003, CAND-010","Intermedio, Junior",PDF
3,MLOps Engineer,2,"CAND-009, CAND-017","Intermedio, Senior","PDF, PNG"

## 5.1 Descripción e interpretación de los perfiles generados

La base de CVs sintéticos quedó organizada en seis tipos principales de perfiles profesionales. La distribución mantiene variedad suficiente para probar el sistema, pero evita una dispersión excesiva de perfiles:

| Tipo de perfil            | Descripción                                                                                                                            |
| ------------------------- | -------------------------------------------------------------------------------------------------------------------------------------- |
| Machine Learning Engineer | Perfiles directamente relacionados con el desarrollo, despliegue, optimización y mantenimiento de modelos de machine learning.         |
| Data Scientist            | Perfiles enfocados en modelado predictivo, análisis estadístico, validación de modelos y generación de conocimiento a partir de datos. |
| Data Engineer             | Perfiles orientados a pipelines de datos, procesamiento distribuido, arquitectura de datos y preparación de información para modelos.  |
| MLOps Engineer            | Perfiles especializados en automatización, monitoreo, versionamiento, despliegue y operación de modelos en producción.                 |
| BI Analyst                | Perfiles centrados en análisis descriptivo, dashboards, indicadores y reportes de negocio.                                             |
| Software Engineer         | Perfiles de desarrollo de software, backend, APIs, cloud, microservicios o arquitectura de sistemas.                                   |

Con esta distribución se busca que el sistema no solo identifique perfiles más directamente alineados con la vacante, sino que también pueda comparar perfiles cercanos y menos cercanos. Esto permitirá evaluar si el ranking final favorece a los candidatos con mayor coincidencia semántica y técnica respecto al puesto seleccionado.

Se generaron cuatro perfiles de Data Engineer, cuatro de Data Scientist, cuatro de Machine Learning Engineer, cuatro de Software Engineer, dos de BI Analyst y dos de MLOps Engineer. Esta distribución permite comparar perfiles altamente relacionados con la vacante, como Machine Learning Engineer y MLOps Engineer, con perfiles cercanos, como Data Scientist y Data Engineer, y perfiles de relación más parcial, como BI Analyst o Software Engineer.

Esta variedad será útil para evaluar si el sistema de búsqueda semántica logra identificar adecuadamente a los candidatos más alineados con la vacante de Lead Machine Learning Engineer y si el ranking final privilegia los perfiles con mayor correspondencia técnica, experiencia relevante y capacidad de trabajo en sistemas productivos de machine learning.

# 6. Generación de documentos PDF y PNG

Una vez definida la estructura de los 20 CVs sintéticos, se procedió a construir los documentos que integrarán la base de conocimiento del sistema. Para cumplir con el enfoque multimodal de la actividad, los CVs se guardarán en dos formatos: PDF y PNG.

La distribución de formatos ya fue definida previamente: 16 documentos se guardarán como PDF y 4 documentos se guardarán como PNG. Los archivos PNG corresponden a 1 perfil Junior, 2 perfiles Intermedio/Semi-Senior y 1 perfil Senior.

En esta sección se genera el contenido completo de cada CV y posteriormente se exporta cada documento al formato correspondiente.

In [108]:
# Se instalan las librerías necesarias para generar los archivos de CVs.
!pip -q install reportlab pillow

In [109]:
# Se crea una lista llamada "cvs_sinteticos" con el contenido completo de los 20 CVs que se usarán como base de conocimiento documental.
# Cada elemento de la lista es un diccionario que representa un candidato.
cvs_sinteticos = [
    {
        "id": "CAND-001",
        "nivel": "Junior",
        "perfil": "Data Scientist",
        "resumen_profesional": "Perfil junior orientado al análisis de datos y construcción inicial de modelos predictivos con Python.",
        "formacion_academica": "Licenciatura en Matemáticas Aplicadas.",
        "experiencia_laboral": "1 año como analista de datos junior, participando en limpieza de datos, visualización y modelos básicos de clasificación.",
        "habilidades_tecnicas": "Python, pandas, NumPy, scikit-learn, SQL, visualización de datos, notebooks.",
        "habilidades_blandas": "Aprendizaje rápido, comunicación, trabajo en equipo, atención al detalle.",
        "certificaciones": "Google Data Analytics Certificate.",
        "idiomas": "Español nativo, inglés intermedio.",
        "proyectos_relevantes": "Modelo de predicción de abandono de clientes usando regresión logística y árboles de decisión."
    },
    {
        "id": "CAND-002",
        "nivel": "Junior",
        "perfil": "Machine Learning Engineer",
        "resumen_profesional": "Perfil junior con bases de machine learning, programación en Python y experiencia inicial integrando modelos en aplicaciones.",
        "formacion_academica": "Licenciatura en Ingeniería en Computación.",
        "experiencia_laboral": "2 años como desarrollador junior en proyectos de automatización y modelos de ML supervisado.",
        "habilidades_tecnicas": "Python, scikit-learn, FastAPI, Git, Docker básico, SQL, pruebas unitarias.",
        "habilidades_blandas": "Resolución de problemas, colaboración, documentación técnica, curiosidad tecnológica.",
        "certificaciones": "Machine Learning Specialization.",
        "idiomas": "Español nativo, inglés intermedio-avanzado.",
        "proyectos_relevantes": "API para servir un modelo de clasificación de tickets de soporte técnico."
    },
    {
        "id": "CAND-003",
        "nivel": "Junior",
        "perfil": "BI Analyst",
        "resumen_profesional": "Perfil junior enfocado en análisis descriptivo, tableros de indicadores y reportes de negocio.",
        "formacion_academica": "Licenciatura en Administración con concentración en Analítica de Negocios.",
        "experiencia_laboral": "1 año elaborando dashboards, reportes comerciales y análisis de ventas.",
        "habilidades_tecnicas": "Power BI, Excel avanzado, SQL básico, Tableau, limpieza de datos.",
        "habilidades_blandas": "Comunicación con usuarios de negocio, organización, pensamiento analítico.",
        "certificaciones": "Microsoft Power BI Data Analyst Associate.",
        "idiomas": "Español nativo, inglés básico.",
        "proyectos_relevantes": "Dashboard ejecutivo de ventas y segmentación básica de clientes."
    },
    {
        "id": "CAND-004",
        "nivel": "Junior",
        "perfil": "Software Engineer",
        "resumen_profesional": "Desarrollador junior con experiencia en backend, APIs y fundamentos de despliegue en la nube.",
        "formacion_academica": "Licenciatura en Ingeniería de Software.",
        "experiencia_laboral": "2 años desarrollando APIs REST y servicios backend para aplicaciones internas.",
        "habilidades_tecnicas": "Python, Java, FastAPI, SQL, Git, Docker básico, pruebas unitarias.",
        "habilidades_blandas": "Trabajo colaborativo, disciplina, documentación, orientación a resultados.",
        "certificaciones": "AWS Cloud Practitioner.",
        "idiomas": "Español nativo, inglés intermedio.",
        "proyectos_relevantes": "Servicio backend para automatización de reportes operativos."
    },
    {
        "id": "CAND-005",
        "nivel": "Junior",
        "perfil": "Data Engineer",
        "resumen_profesional": "Perfil junior orientado a integración de datos, construcción de ETL y soporte a equipos analíticos.",
        "formacion_academica": "Licenciatura en Ciencia de Datos.",
        "experiencia_laboral": "2 años apoyando la construcción de pipelines batch y procesos de limpieza de datos.",
        "habilidades_tecnicas": "SQL, Python, pandas, Airflow básico, Spark básico, Git.",
        "habilidades_blandas": "Orden, pensamiento lógico, colaboración, aprendizaje continuo.",
        "certificaciones": "Databricks Lakehouse Fundamentals.",
        "idiomas": "Español nativo, inglés intermedio.",
        "proyectos_relevantes": "Pipeline ETL para consolidación de datos de ventas y clientes."
    },
    {
        "id": "CAND-006",
        "nivel": "Intermedio",
        "perfil": "Machine Learning Engineer",
        "resumen_profesional": "Ingeniero de machine learning con experiencia en entrenamiento, validación y despliegue inicial de modelos predictivos.",
        "formacion_academica": "Ingeniería en Computación.",
        "experiencia_laboral": "4 años desarrollando modelos supervisados, APIs de inferencia y procesos de evaluación de modelos.",
        "habilidades_tecnicas": "Python, scikit-learn, PyTorch básico, Docker, FastAPI, MLflow, SQL, AWS.",
        "habilidades_blandas": "Comunicación técnica, trabajo ágil, solución de problemas, colaboración con producto.",
        "certificaciones": "AWS Machine Learning Specialty.",
        "idiomas": "Español nativo, inglés avanzado.",
        "proyectos_relevantes": "Modelo de scoring de clientes desplegado mediante API y monitoreado con métricas de desempeño."
    },
    {
        "id": "CAND-007",
        "nivel": "Intermedio",
        "perfil": "Data Scientist",
        "resumen_profesional": "Científico de datos con experiencia en modelos predictivos, experimentación y análisis estadístico aplicado a negocio.",
        "formacion_academica": "Maestría en Ciencia de Datos.",
        "experiencia_laboral": "5 años construyendo modelos de clasificación, regresión y segmentación para áreas comerciales y financieras.",
        "habilidades_tecnicas": "Python, scikit-learn, XGBoost, SQL, pandas, experimentación A/B, visualización.",
        "habilidades_blandas": "Pensamiento crítico, comunicación con negocio, storytelling con datos.",
        "certificaciones": "Professional Data Scientist Certification.",
        "idiomas": "Español nativo, inglés avanzado.",
        "proyectos_relevantes": "Modelo de propensión de compra y segmentación de clientes para campañas personalizadas."
    },
    {
        "id": "CAND-008",
        "nivel": "Intermedio",
        "perfil": "Data Engineer",
        "resumen_profesional": "Ingeniero de datos con experiencia en pipelines productivos, procesamiento distribuido y ambientes cloud.",
        "formacion_academica": "Ingeniería en Sistemas Computacionales.",
        "experiencia_laboral": "4 años construyendo pipelines de datos, procesos ETL y modelos de datos para analítica avanzada.",
        "habilidades_tecnicas": "Python, SQL, Spark, Airflow, AWS Glue, S3, Redshift, Docker.",
        "habilidades_blandas": "Organización, colaboración con equipos de datos, pensamiento estructurado.",
        "certificaciones": "AWS Data Analytics Specialty.",
        "idiomas": "Español nativo, inglés intermedio-avanzado.",
        "proyectos_relevantes": "Pipeline distribuido para procesamiento diario de transacciones y generación de features para modelos."
    },
    {
        "id": "CAND-009",
        "nivel": "Intermedio",
        "perfil": "MLOps Engineer",
        "resumen_profesional": "Ingeniero MLOps con experiencia en automatización, despliegue, monitoreo y mantenimiento de modelos de ML.",
        "formacion_academica": "Ingeniería en Computación.",
        "experiencia_laboral": "5 años trabajando en infraestructura para modelos, CI/CD, contenedores y monitoreo de servicios de inferencia.",
        "habilidades_tecnicas": "Python, Docker, Kubernetes, MLflow, GitHub Actions, AWS, FastAPI, monitoreo de modelos.",
        "habilidades_blandas": "Colaboración con ciencia de datos, orientación a confiabilidad, documentación técnica.",
        "certificaciones": "Kubernetes Application Developer.",
        "idiomas": "Español nativo, inglés avanzado.",
        "proyectos_relevantes": "Plataforma interna para registrar, versionar, desplegar y monitorear modelos de machine learning."
    },
    {
        "id": "CAND-010",
        "nivel": "Intermedio",
        "perfil": "BI Analyst",
        "resumen_profesional": "Analista BI con experiencia en tableros ejecutivos, modelado dimensional y análisis descriptivo de negocio.",
        "formacion_academica": "Licenciatura en Economía.",
        "experiencia_laboral": "4 años desarrollando reportes, KPIs y dashboards para áreas comerciales.",
        "habilidades_tecnicas": "Power BI, Tableau, SQL, Excel avanzado, modelado dimensional básico.",
        "habilidades_blandas": "Comunicación ejecutiva, análisis de negocio, atención al usuario.",
        "certificaciones": "Tableau Desktop Specialist.",
        "idiomas": "Español nativo, inglés intermedio.",
        "proyectos_relevantes": "Sistema de indicadores de ventas y rentabilidad por región."
    },
    {
        "id": "CAND-011",
        "nivel": "Intermedio",
        "perfil": "Software Engineer",
        "resumen_profesional": "Ingeniero de software con experiencia en backend, APIs, servicios cloud y buenas prácticas de desarrollo.",
        "formacion_academica": "Ingeniería en Software.",
        "experiencia_laboral": "5 años desarrollando servicios backend, integraciones y automatización de procesos.",
        "habilidades_tecnicas": "Java, Python, Spring Boot, FastAPI, Docker, AWS, SQL, pruebas automatizadas.",
        "habilidades_blandas": "Trabajo en equipo, documentación, comunicación técnica, pensamiento sistémico.",
        "certificaciones": "AWS Developer Associate.",
        "idiomas": "Español nativo, inglés avanzado.",
        "proyectos_relevantes": "Microservicio para procesamiento de solicitudes y validación automática de reglas de negocio."
    },
    {
        "id": "CAND-012",
        "nivel": "Intermedio",
        "perfil": "Machine Learning Engineer",
        "resumen_profesional": "Ingeniero de machine learning con experiencia en modelos productivos, pipelines de entrenamiento y despliegue cloud.",
        "formacion_academica": "Maestría en Inteligencia Artificial Aplicada.",
        "experiencia_laboral": "5 años desarrollando soluciones de ML para predicción, clasificación y optimización operativa.",
        "habilidades_tecnicas": "Python, PyTorch, scikit-learn, TensorFlow, MLflow, Docker, AWS, CI/CD.",
        "habilidades_blandas": "Liderazgo técnico inicial, colaboración ágil, comunicación con stakeholders.",
        "certificaciones": "TensorFlow Developer Certificate.",
        "idiomas": "Español nativo, inglés avanzado.",
        "proyectos_relevantes": "Pipeline de entrenamiento y despliegue de modelo de predicción de demanda en AWS."
    },
    {
        "id": "CAND-013",
        "nivel": "Intermedio",
        "perfil": "Data Scientist",
        "resumen_profesional": "Científico de datos con experiencia en modelado predictivo, procesamiento de datos y evaluación de desempeño de modelos.",
        "formacion_academica": "Licenciatura en Actuaría.",
        "experiencia_laboral": "3 años desarrollando modelos de riesgo, segmentación y predicción de comportamiento de usuarios.",
        "habilidades_tecnicas": "Python, SQL, scikit-learn, pandas, estadística, visualización, validación cruzada.",
        "habilidades_blandas": "Comunicación analítica, pensamiento matemático, colaboración interdisciplinaria.",
        "certificaciones": "Applied Data Science with Python.",
        "idiomas": "Español nativo, inglés intermedio-avanzado.",
        "proyectos_relevantes": "Modelo de riesgo para priorización de clientes y análisis de variables explicativas."
    },
    {
        "id": "CAND-014",
        "nivel": "Intermedio",
        "perfil": "Data Engineer",
        "resumen_profesional": "Ingeniero de datos con experiencia en arquitectura de datos, pipelines batch y streaming, y soporte a modelos analíticos.",
        "formacion_academica": "Ingeniería en Tecnologías de Información.",
        "experiencia_laboral": "5 años construyendo pipelines en cloud, integrando fuentes de datos y preparando datasets para ciencia de datos.",
        "habilidades_tecnicas": "Python, Spark, Airflow, Kafka, SQL, AWS, Databricks, Docker.",
        "habilidades_blandas": "Trabajo con equipos multidisciplinarios, documentación, pensamiento estructurado.",
        "certificaciones": "Databricks Data Engineer Associate.",
        "idiomas": "Español nativo, inglés avanzado.",
        "proyectos_relevantes": "Feature store para modelos de machine learning alimentado por pipelines de datos."
    },
    {
        "id": "CAND-015",
        "nivel": "Intermedio",
        "perfil": "Software Engineer",
        "resumen_profesional": "Ingeniero de software orientado a backend y arquitectura de servicios, con experiencia parcial en integración de modelos.",
        "formacion_academica": "Licenciatura en Ciencias Computacionales.",
        "experiencia_laboral": "4 años desarrollando APIs, servicios internos y automatización de procesos empresariales.",
        "habilidades_tecnicas": "Java, Python, REST APIs, Docker, Git, SQL, Azure básico.",
        "habilidades_blandas": "Resolución de problemas, colaboración, documentación, adaptabilidad.",
        "certificaciones": "Microsoft Azure Fundamentals.",
        "idiomas": "Español nativo, inglés intermedio.",
        "proyectos_relevantes": "API para integrar resultados de modelos analíticos en un sistema operativo interno."
    },
    {
        "id": "CAND-016",
        "nivel": "Senior",
        "perfil": "Lead Machine Learning Engineer",
        "resumen_profesional": "Perfil senior especializado en diseño, despliegue y operación de sistemas de machine learning en producción.",
        "formacion_academica": "Maestría en Ciencias de la Computación.",
        "experiencia_laboral": "8 años liderando proyectos de machine learning, MLOps, arquitectura cloud y sistemas distribuidos.",
        "habilidades_tecnicas": "Python, PyTorch, TensorFlow, Spark, MLflow, Kubernetes, AWS, CI/CD, monitoreo de modelos.",
        "habilidades_blandas": "Liderazgo técnico, mentoría, comunicación estratégica, colaboración con producto y negocio.",
        "certificaciones": "AWS Machine Learning Specialty; Certified Kubernetes Administrator.",
        "idiomas": "Español nativo, inglés avanzado.",
        "proyectos_relevantes": "Arquitectura integral para entrenamiento, despliegue, monitoreo y reentrenamiento de modelos de riesgo en producción."
    },
    {
        "id": "CAND-017",
        "nivel": "Senior",
        "perfil": "MLOps Engineer",
        "resumen_profesional": "Especialista senior en MLOps, plataformas de modelos, automatización de despliegues y confiabilidad operacional.",
        "formacion_academica": "Ingeniería en Computación con especialidad en sistemas distribuidos.",
        "experiencia_laboral": "7 años implementando infraestructura para modelos de ML, CI/CD, monitoreo, versionamiento y gobernanza.",
        "habilidades_tecnicas": "Python, Docker, Kubernetes, MLflow, Kubeflow, AWS, Terraform, GitHub Actions, monitoreo.",
        "habilidades_blandas": "Orientación a confiabilidad, liderazgo técnico, colaboración con equipos de ciencia de datos.",
        "certificaciones": "AWS Solutions Architect Associate; MLOps Specialization.",
        "idiomas": "Español nativo, inglés avanzado.",
        "proyectos_relevantes": "Plataforma MLOps para ciclo de vida completo de modelos, incluyendo registro, aprobación, despliegue y monitoreo."
    },
    {
        "id": "CAND-018",
        "nivel": "Senior",
        "perfil": "Data Architect",
        "resumen_profesional": "Arquitecto de datos con experiencia senior en soluciones intensivas en datos, cloud y sistemas distribuidos.",
        "formacion_academica": "Maestría en Ingeniería de Datos.",
        "experiencia_laboral": "9 años diseñando arquitecturas de datos, lagos de datos, pipelines distribuidos y plataformas analíticas.",
        "habilidades_tecnicas": "Spark, Python, SQL, AWS, Redshift, Databricks, Airflow, Kafka, modelado de datos.",
        "habilidades_blandas": "Liderazgo técnico, visión arquitectónica, comunicación con áreas de negocio.",
        "certificaciones": "AWS Data Analytics Specialty; Databricks Data Engineer Professional.",
        "idiomas": "Español nativo, inglés avanzado.",
        "proyectos_relevantes": "Arquitectura de datos para alimentar modelos de machine learning y tableros analíticos corporativos."
    },
    {
        "id": "CAND-019",
        "nivel": "Senior",
        "perfil": "Data Scientist",
        "resumen_profesional": "Científico de datos senior con experiencia en modelado predictivo, interpretación de modelos y liderazgo de proyectos analíticos.",
        "formacion_academica": "Doctorado en Estadística Aplicada.",
        "experiencia_laboral": "7 años desarrollando modelos predictivos, modelos de riesgo, experimentación y análisis avanzado.",
        "habilidades_tecnicas": "Python, scikit-learn, PyTorch, XGBoost, estadística, explainable AI, SQL, MLflow.",
        "habilidades_blandas": "Liderazgo analítico, comunicación ejecutiva, mentoría, pensamiento crítico.",
        "certificaciones": "Responsible AI Professional Certificate.",
        "idiomas": "Español nativo, inglés avanzado.",
        "proyectos_relevantes": "Modelo explicable de riesgo crediticio con análisis de importancia de variables y monitoreo de desempeño."
    },
    {
        "id": "CAND-020",
        "nivel": "Senior",
        "perfil": "Software Architect",
        "resumen_profesional": "Arquitecto de software senior con experiencia en sistemas distribuidos, cloud, APIs y diseño de plataformas escalables.",
        "formacion_academica": "Ingeniería en Sistemas Computacionales.",
        "experiencia_laboral": "10 años diseñando arquitecturas backend, microservicios y plataformas empresariales en cloud.",
        "habilidades_tecnicas": "Java, Python, AWS, Kubernetes, microservicios, CI/CD, Docker, APIs, arquitectura distribuida.",
        "habilidades_blandas": "Liderazgo técnico, toma de decisiones arquitectónicas, mentoría, comunicación con stakeholders.",
        "certificaciones": "AWS Solutions Architect Professional.",
        "idiomas": "Español nativo, inglés avanzado.",
        "proyectos_relevantes": "Plataforma de microservicios para procesamiento de datos e integración de componentes analíticos."
    }
]

# Se convierte la lista de CVs sintéticos en un DataFrame.
df_cvs = pd.DataFrame(cvs_sinteticos)

# Se muestran los primeros registros para verificar que la tabla fue creada correctamente.
df_cvs.head()

,id,nivel,perfil,resumen_profesional,formacion_academica,experiencia_laboral,habilidades_tecnicas,habilidades_blandas,certificaciones,idiomas,proyectos_relevantes
0,CAND-001,Junior,Data Scientist,Perfil junior orientado al análisis de datos y...,Licenciatura en Matemáticas Aplicadas.,"1 año como analista de datos junior, participa...","Python, pandas, NumPy, scikit-learn, SQL, visu...","Aprendizaje rápido, comunicación, trabajo en e...",Google Data Analytics Certificate.,"Español nativo, inglés intermedio.",Modelo de predicción de abandono de clientes u...
1,CAND-002,Junior,Machine Learning Engineer,"Perfil junior con bases de machine learning, p...",Licenciatura en Ingeniería en Computación.,2 años como desarrollador junior en proyectos ...,"Python, scikit-learn, FastAPI, Git, Docker bás...","Resolución de problemas, colaboración, documen...",Machine Learning Specialization.,"Español nativo, inglés intermedio-avanzado.",API para servir un modelo de clasificación de ...
2,CAND-003,Junior,BI Analyst,Perfil junior enfocado en análisis descriptivo...,Licenciatura en Administración con concentraci...,"1 año elaborando dashboards, reportes comercia...","Power BI, Excel avanzado, SQL básico, Tableau,...","Comunicación con usuarios de negocio, organiza...",Microsoft Power BI Data Analyst Associate.,"Español nativo, inglés básico.",Dashboard ejecutivo de ventas y segmentación b...
3,CAND-004,Junior,Software Engineer,Desarrollador junior con experiencia en backen...,Licenciatura en Ingeniería de Software.,2 años desarrollando APIs REST y servicios bac...,"Python, Java, FastAPI, SQL, Git, Docker básico...","Trabajo colaborativo, disciplina, documentació...",AWS Cloud Practitioner.,"Español nativo, inglés intermedio.",Servicio backend para automatización de report...
4,CAND-005,Junior,Data Engineer,Perfil junior orientado a integración de datos...,Licenciatura en Ciencia de Datos.,2 años apoyando la construcción de pipelines b...,"SQL, Python, pandas, Airflow básico, Spark bás...","Orden, pensamiento lógico, colaboración, apren...",Databricks Lakehouse Fundamentals.,"Español nativo, inglés intermedio.",Pipeline ETL para consolidación de datos de ve...

## 6.1 Exportación de los CVs sintéticos

A partir del DataFrame `df_cvs`, se exportaron los 20 CVs sintéticos como documentos individuales. Para respetar la distribución definida en la actividad, se utilizaron 16 archivos en formato PDF y 4 archivos en formato PNG.

Cada archivo conserva el identificador anónimo del candidato y contiene únicamente información profesional relevante. Estos documentos integrarán la base de conocimiento que será utilizada posteriormente para la extracción de texto, construcción de embeddings, búsqueda semántica y ranking de candidatos.

In [110]:
import os
import textwrap
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from PIL import Image, ImageDraw, ImageFont

# Crear carpeta de salida
carpeta_cvs = "base_conocimiento_cvs"
os.makedirs(carpeta_cvs, exist_ok=True)

# Unir el contenido completo de los CVs con el diseño de formatos
df_cvs_export = df_cvs.merge(
    df_diseno_cvs[["id", "formato", "alineacion_esperada", "experiencia_anios"]],
    on="id",
    how="left"
)

# Esta función construye el texto completo de cada CV.
# Recibe una fila del DataFrame y organiza la información en formato de CV.
def construir_texto_cv(fila):
    texto = f"""
CV SINTÉTICO - {fila['id']}

Nivel: {fila['nivel']}
Perfil: {fila['perfil']}
Años de experiencia: {fila['experiencia_anios']}
Alineación esperada con la vacante: {fila['alineacion_esperada']}

Resumen profesional:
{fila['resumen_profesional']}

Formación académica:
{fila['formacion_academica']}

Experiencia laboral:
{fila['experiencia_laboral']}

Habilidades técnicas:
{fila['habilidades_tecnicas']}

Habilidades blandas:
{fila['habilidades_blandas']}

Certificaciones:
{fila['certificaciones']}

Idiomas:
{fila['idiomas']}

Proyectos relevantes:
{fila['proyectos_relevantes']}
"""

# Se eliminan espacios innecesarios al inicio y al final del texto.
    return texto.strip()

# Esta función guarda el texto de un CV en formato PDF.
def guardar_pdf(texto, ruta_pdf):
    doc = SimpleDocTemplate(ruta_pdf, pagesize=letter)
    estilos = getSampleStyleSheet()
    elementos = []

    for bloque in texto.split("\n"):
        if bloque.strip() == "":
            elementos.append(Spacer(1, 8))
        else:
            elementos.append(Paragraph(bloque, estilos["Normal"]))
            elementos.append(Spacer(1, 6))

    doc.build(elementos)


# Esta función guarda el texto de un CV en formato PNG.
def guardar_png(texto, ruta_png):
    ancho, alto = 1200, 1600
    imagen = Image.new("RGB", (ancho, alto), "white")
    draw = ImageDraw.Draw(imagen)

    try:
        fuente_titulo = ImageFont.truetype("DejaVuSans-Bold.ttf", 34)
        fuente_texto = ImageFont.truetype("DejaVuSans.ttf", 26)
    except:
        fuente_titulo = ImageFont.load_default()
        fuente_texto = ImageFont.load_default()

    x, y = 60, 60
    lineas = []

    for parrafo in texto.split("\n"):
        if parrafo.strip() == "":
            lineas.append("")
        else:
            lineas.extend(textwrap.wrap(parrafo, width=70))

    for i, linea in enumerate(lineas):
        fuente = fuente_titulo if i == 0 else fuente_texto
        draw.text((x, y), linea, fill="black", font=fuente)
        y += 42

        if y > alto - 80:
            break

    imagen.save(ruta_png)

# Exportar archivos
archivos_generados = []

for _, fila in df_cvs_export.iterrows():
    texto_cv = construir_texto_cv(fila)

    if fila["formato"] == "PDF":
        nombre_archivo = f"{fila['id']}_{fila['perfil'].replace(' ', '_')}.pdf"
        ruta_archivo = os.path.join(carpeta_cvs, nombre_archivo)
        guardar_pdf(texto_cv, ruta_archivo)

    elif fila["formato"] == "PNG":
        nombre_archivo = f"{fila['id']}_{fila['perfil'].replace(' ', '_')}.png"
        ruta_archivo = os.path.join(carpeta_cvs, nombre_archivo)
        guardar_png(texto_cv, ruta_archivo)

    archivos_generados.append({
        "id": fila["id"],
        "perfil": fila["perfil"],
        "nivel": fila["nivel"],
        "formato": fila["formato"],
        "archivo": ruta_archivo
    })

# Se convierte la lista de archivos generados en un DataFrame.
df_archivos = pd.DataFrame(archivos_generados)

# Se muestra la tabla completa de archivos generados.
df_archivos.head(20)

,id,perfil,nivel,formato,archivo
0,CAND-001,Data Scientist,Junior,PNG,base_conocimiento_cvs/CAND-001_Data_Scientist.png
1,CAND-002,Machine Learning Engineer,Junior,PDF,base_conocimiento_cvs/CAND-002_Machine_Learnin...
2,CAND-003,BI Analyst,Junior,PDF,base_conocimiento_cvs/CAND-003_BI_Analyst.pdf
3,CAND-004,Software Engineer,Junior,PDF,base_conocimiento_cvs/CAND-004_Software_Engine...
4,CAND-005,Data Engineer,Junior,PDF,base_conocimiento_cvs/CAND-005_Data_Engineer.pdf
5,CAND-006,Machine Learning Engineer,Intermedio,PNG,base_conocimiento_cvs/CAND-006_Machine_Learnin...
6,CAND-007,Data Scientist,Intermedio,PDF,base_conocimiento_cvs/CAND-007_Data_Scientist.pdf
7,CAND-008,Data Engineer,Intermedio,PDF,base_conocimiento_cvs/CAND-008_Data_Engineer.pdf
8,CAND-009,MLOps Engineer,Intermedio,PNG,base_conocimiento_cvs/CAND-009_MLOps_Engineer.png
9,CAND-010,BI Analyst,Intermedio,PDF,base_conocimiento_cvs/CAND-010_BI_Analyst.pdf
10,CAND-011,Software Engineer,Intermedio,PDF,base_conocimiento_cvs/CAND-011_Software_Engine...
11,CAND-012,Machine Learning Engineer,Intermedio,PDF,base_conocimiento_cvs/CAND-012_Machine_Learnin...
12,CAND-013,Data Scientist,Intermedio,PDF,base_conocimiento_cvs/CAND-013_Data_Scientist.pdf
13,CAND-014,Data Engineer,Intermedio,PDF,base_conocimiento_cvs/CAND-014_Data_Engineer.pdf
14,CAND-015,Software Engineer,Intermedio,PDF,base_conocimiento_cvs/CAND-015_Software_Engine...
15,CAND-016,Lead Machine Learning Engineer,Senior,PNG,base_conocimiento_cvs/CAND-016_Lead_Machine_Le...
16,CAND-017,MLOps Engineer,Senior,PDF,base_conocimiento_cvs/CAND-017_MLOps_Engineer.pdf
17,CAND-018,Data Architect,Senior,PDF,base_conocimiento_cvs/CAND-018_Data_Architect.pdf
18,CAND-019,Data Scientist,Senior,PDF,base_conocimiento_cvs/CAND-019_Data_Scientist.pdf
19,CAND-020,Software Architect,Senior,PDF,base_conocimiento_cvs/CAND-020_Software_Archit...

In [111]:
# Se verifica el número total de archivos generados y la distribución de archivos por formato.
print("Total de archivos generados:", len(df_archivos))
print("\nDistribución por formato:")
display(df_archivos["formato"].value_counts())

# Se muestra la tabla completa de archivos generados.
print("\nArchivos generados:")
display(df_archivos)

# Validaciones automáticas de la base documental.
assert len(df_archivos) == 20, "Deben generarse exactamente 20 archivos."
assert df_archivos["formato"].value_counts()["PDF"] == 16, "Deben generarse 16 archivos PDF."
assert df_archivos["formato"].value_counts()["PNG"] == 4, "Deben generarse 4 archivos PNG."
assert df_archivos["archivo"].apply(os.path.exists).all(), "Todos los archivos registrados deben existir."

Total de archivos generados: 20

Distribución por formato:

formato
PDF    16
PNG     4
Name: count, dtype: int64

Archivos generados:

,id,perfil,nivel,formato,archivo
0,CAND-001,Data Scientist,Junior,PNG,base_conocimiento_cvs/CAND-001_Data_Scientist.png
1,CAND-002,Machine Learning Engineer,Junior,PDF,base_conocimiento_cvs/CAND-002_Machine_Learnin...
2,CAND-003,BI Analyst,Junior,PDF,base_conocimiento_cvs/CAND-003_BI_Analyst.pdf
3,CAND-004,Software Engineer,Junior,PDF,base_conocimiento_cvs/CAND-004_Software_Engine...
4,CAND-005,Data Engineer,Junior,PDF,base_conocimiento_cvs/CAND-005_Data_Engineer.pdf
5,CAND-006,Machine Learning Engineer,Intermedio,PNG,base_conocimiento_cvs/CAND-006_Machine_Learnin...
6,CAND-007,Data Scientist,Intermedio,PDF,base_conocimiento_cvs/CAND-007_Data_Scientist.pdf
7,CAND-008,Data Engineer,Intermedio,PDF,base_conocimiento_cvs/CAND-008_Data_Engineer.pdf
8,CAND-009,MLOps Engineer,Intermedio,PNG,base_conocimiento_cvs/CAND-009_MLOps_Engineer.png
9,CAND-010,BI Analyst,Intermedio,PDF,base_conocimiento_cvs/CAND-010_BI_Analyst.pdf
10,CAND-011,Software Engineer,Intermedio,PDF,base_conocimiento_cvs/CAND-011_Software_Engine...
11,CAND-012,Machine Learning Engineer,Intermedio,PDF,base_conocimiento_cvs/CAND-012_Machine_Learnin...
12,CAND-013,Data Scientist,Intermedio,PDF,base_conocimiento_cvs/CAND-013_Data_Scientist.pdf
13,CAND-014,Data Engineer,Intermedio,PDF,base_conocimiento_cvs/CAND-014_Data_Engineer.pdf
14,CAND-015,Software Engineer,Intermedio,PDF,base_conocimiento_cvs/CAND-015_Software_Engine...
15,CAND-016,Lead Machine Learning Engineer,Senior,PNG,base_conocimiento_cvs/CAND-016_Lead_Machine_Le...
16,CAND-017,MLOps Engineer,Senior,PDF,base_conocimiento_cvs/CAND-017_MLOps_Engineer.pdf
17,CAND-018,Data Architect,Senior,PDF,base_conocimiento_cvs/CAND-018_Data_Architect.pdf
18,CAND-019,Data Scientist,Senior,PDF,base_conocimiento_cvs/CAND-019_Data_Scientist.pdf
19,CAND-020,Software Architect,Senior,PDF,base_conocimiento_cvs/CAND-020_Software_Archit...

## 6.2 Verificación de la base de conocimiento documental

La exportación de los CVs sintéticos generó un total de 20 archivos individuales dentro de la carpeta `base_conocimiento_cvs`. La distribución final cumple con lo solicitado para la actividad: 16 documentos en formato PDF y 4 documentos en formato PNG.

Esta base documental será utilizada como entrada para el sistema multimodal inteligente. En las siguientes secciones, el sistema extraerá texto de los documentos PDF y de las imágenes PNG, construirá una representación textual de cada candidato y generará una base vectorial para realizar búsqueda semántica contra la vacante seleccionada.

In [112]:
# Se importa shutil para comprimir carpetas y generar archivos ZIP.
import shutil

# Se importa files de Google Colab para descargar el archivo ZIP generado.
from google.colab import files

# Se comprime la carpeta "base_conocimiento_cvs" en un archivo ZIP.
ruta_zip = shutil.make_archive(
    "base_conocimiento_cvs",
    "zip",
    carpeta_cvs
)

# Se muestra la ruta del archivo ZIP generado.
print("Archivo ZIP generado:", ruta_zip)

# Se descarga el archivo ZIP desde Google Colab.
# Este archivo puede entregarse junto con el notebook como evidencia de la base de conocimiento documental creada para la actividad.
files.download("base_conocimiento_cvs.zip")

Archivo ZIP generado: /content/base_conocimiento_cvs.zip

Además de generar los archivos individuales, se creó un archivo comprimido `base_conocimiento_cvs.zip` con todos los documentos PDF y PNG. Este archivo puede entregarse junto con el notebook como evidencia de la base de conocimiento documental.

# 7. Sistema multimodal inteligente para búsqueda y selección de candidatos

## 7.1 Extracción de texto desde documentos PDF y PNG

Para construir la base textual de candidatos, el sistema extrae información de los documentos generados en la base de conocimiento. En el caso de los archivos PDF se recupera el texto directamente mediante `pypdf`; en el caso de los archivos PNG se utiliza OCR mediante `pytesseract`.

Esta etapa permite integrar documentos de formatos distintos dentro de una misma representación textual, lo cual es necesario para construir posteriormente la base vectorial y realizar la búsqueda semántica.

En esta sección se implementa el sistema inteligente para analizar los CVs sintéticos y recomendar los 5 candidatos más adecuados para la vacante seleccionada.

La arquitectura del sistema se compone de las siguientes etapas:

| Etapa | Descripción |
|---|---|
| Entrada documental | Se utilizan los 20 CVs sintéticos generados previamente, en formato PDF y PNG. |
| Extracción de texto | Se extrae texto directamente desde los PDF y mediante OCR desde los PNG. |
| Base textual | Se construye una tabla con el contenido textual de cada CV. |
| Representación vectorial | Se generan embeddings semánticos para cada CV y para la vacante. |
| Búsqueda semántica | Se calcula la similitud entre la vacante y cada CV. |
| Ranking | Se ordenan los candidatos según su similitud semántica con la vacante. |
| Selección final | Se obtiene un Top 5 de candidatos recomendados con base en su alineación con el puesto. |

El sistema no sustituye la decisión del reclutador, sino que funciona como una herramienta de apoyo para priorizar perfiles y facilitar la revisión inicial.

In [113]:
# Se actualizan los paquetes disponibles en el entorno de Google Colab.
# Tesseract se utilizará para extraer texto de los CVs guardados como imágenes PNG.
!apt-get -qq update
!apt-get -qq install -y tesseract-ocr tesseract-ocr-spa
!pip -q install pypdf pytesseract sentence-transformers scikit-learn

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

In [114]:
from pypdf import PdfReader
from PIL import Image
import pytesseract
import pandas as pd
import numpy as np
import os

# Esta función extrae texto de un archivo PDF.
def extraer_texto_pdf(ruta_pdf):
    reader = PdfReader(ruta_pdf)
    texto = ""

    for page in reader.pages:
        texto += page.extract_text() or ""

    return texto.strip()

# Esta función extrae texto de un archivo PNG mediante OCR.
def extraer_texto_png(ruta_png):
    imagen = Image.open(ruta_png)
    texto = pytesseract.image_to_string(imagen, lang="spa")
    return texto.strip()

# Esta función decide qué método de extracción usar según el formato del archivo.
def extraer_texto_documento(ruta, formato):
    if formato == "PDF":
        return extraer_texto_pdf(ruta)
    elif formato == "PNG":
        return extraer_texto_png(ruta)
    else:
        return ""

# Se crea una lista vacía para almacenar los documentos procesados.
documentos_procesados = []

for _, fila in df_archivos.iterrows():
    texto_extraido = extraer_texto_documento(fila["archivo"], fila["formato"])

    documentos_procesados.append({
        "id": fila["id"],
        "perfil": fila["perfil"],
        "nivel": fila["nivel"],
        "formato": fila["formato"],
        "archivo": fila["archivo"],
        "texto_extraido": texto_extraido,
        "longitud_texto": len(texto_extraido)
    })

# Se convierte la lista de documentos procesados en un DataFrame.
df_documentos = pd.DataFrame(documentos_procesados)

# Se valida que se hayan procesado 20 documentos.
assert len(df_documentos) == 20, "Deben procesarse exactamente 20 documentos."


# Se valida que todos los documentos tengan texto extraído.
# Si algún documento tiene longitud 0, significa que falló la extracción de texto.
assert (df_documentos["longitud_texto"] > 0).all(), "Hay documentos sin texto extraído."


# Se muestra una tabla de verificación con la longitud del texto extraído.
# Esto permite revisar que tanto PDFs como PNGs fueron procesados correctamente.
df_documentos[
    [
        "id",
        "perfil",
        "nivel",
        "formato",
        "longitud_texto"
    ]
].head(20)

,id,perfil,nivel,formato,longitud_texto
0,CAND-001,Data Scientist,Junior,PNG,833
1,CAND-002,Machine Learning Engineer,Junior,PDF,864
2,CAND-003,BI Analyst,Junior,PDF,796
3,CAND-004,Software Engineer,Junior,PDF,757
4,CAND-005,Data Engineer,Junior,PDF,748
5,CAND-006,Machine Learning Engineer,Intermedio,PNG,835
6,CAND-007,Data Scientist,Intermedio,PDF,855
7,CAND-008,Data Engineer,Intermedio,PDF,843
8,CAND-009,MLOps Engineer,Intermedio,PNG,844
9,CAND-010,BI Analyst,Intermedio,PDF,749
10,CAND-011,Software Engineer,Intermedio,PDF,808
11,CAND-012,Machine Learning Engineer,Intermedio,PDF,848
12,CAND-013,Data Scientist,Intermedio,PDF,859
13,CAND-014,Data Engineer,Intermedio,PDF,858
14,CAND-015,Software Engineer,Intermedio,PDF,815
15,CAND-016,Lead Machine Learning Engineer,Senior,PNG,911
16,CAND-017,MLOps Engineer,Senior,PDF,955
17,CAND-018,Data Architect,Senior,PDF,888
18,CAND-019,Data Scientist,Senior,PDF,879
19,CAND-020,Software Architect,Senior,PDF,902

## 7.2 Construcción de la base vectorial

Para esta actividad, la base vectorial se implementó como una matriz de embeddings almacenada en memoria, asociada a un DataFrame con los metadatos de cada candidato. En una implementación productiva, esta misma lógica podría migrarse a una base vectorial especializada como FAISS, ChromaDB, Pinecone o Weaviate.

Una vez extraído el texto de los documentos PDF y PNG, se construye una base vectorial de candidatos. Para ello, se utiliza un modelo de embeddings multilingüe capaz de representar semánticamente tanto la vacante como los CVs.

La consulta principal del sistema será la síntesis de la vacante seleccionada, enriquecida con sus competencias clave. Cada CV será comparado contra esa consulta mediante similitud coseno.

In [115]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Se construye el texto de consulta de la vacante.
consulta_vacante = (
    vacante["descripcion_sintetica"]
    + " "
    + " ".join(vacante["competencias_clave"])
)

# Se carga un modelo multilingüe de embeddings.
modelo_embeddings = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

textos_cvs = df_documentos["texto_extraido"].tolist()

embeddings_cvs = modelo_embeddings.encode(
    textos_cvs,
    show_progress_bar=True,
    normalize_embeddings=True
)

embedding_vacante = modelo_embeddings.encode(
    [consulta_vacante],
    normalize_embeddings=True
)

# Se calcula la similitud coseno entre la vacante y cada CV.
similitudes = cosine_similarity(embedding_vacante, embeddings_cvs)[0]

df_ranking = df_documentos.copy()

df_ranking["similitud_semantica"] = similitudes
df_ranking["similitud_porcentaje"] = (
    df_ranking["similitud_semantica"] * 100
).round(2)

df_ranking = df_ranking.sort_values(
    "similitud_semantica",
    ascending=False
).reset_index(drop=True)

# Se muestra el Top 10 del ranking semántico inicial.
df_ranking[
    [
        "id",
        "perfil",
        "nivel",
        "formato",
        "similitud_porcentaje"
    ]
].head(10).style.format({
    "similitud_porcentaje": "{:.2f}"
})

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

## 7.3 Ranking inicial de candidatos

El ranking se obtiene comparando semánticamente el contenido extraído de cada CV contra la descripción sintética de la vacante. Los candidatos con mayor similitud semántica son considerados más alineados con los requisitos del puesto.

Este ranking será revisado posteriormente desde una perspectiva técnica, considerando si los perfiles recomendados tienen experiencia suficiente en machine learning, MLOps, cloud, pipelines de datos, programación, sistemas distribuidos y liderazgo técnico.

In [116]:
# Se seleccionan los primeros 5 candidatos del ranking semántico inicial.
top5_candidatos = df_ranking.head(5).copy()

# Se muestra el Top 5 inicial con las columnas principales.
top5_candidatos[
    [
        "id",
        "perfil",
        "nivel",
        "formato",
        "similitud_porcentaje"
    ]
].style.format({
    "similitud_porcentaje": "{:.2f}"
})

## 7.4 Ajuste técnico del ranking semántico

El ranking semántico inicial permite identificar candidatos cuyo contenido textual es parecido a la vacante. Sin embargo, para una posición de nivel Lead, la similitud textual no es suficiente. Es necesario considerar también experiencia, nivel profesional, liderazgo técnico, MLOps, cloud computing, CI/CD, sistemas distribuidos, pipelines de datos y uso de frameworks de machine learning.

Por esta razón, se construyó un ranking final ponderado que combina la similitud semántica con criterios técnicos derivados de los requisitos de la vacante.

In [117]:
# Construir tabla auxiliar con información completa de cada CV
df_info_cvs = df_cvs.merge(
    df_diseno_cvs[["id", "experiencia_anios", "alineacion_esperada"]],
    on="id",
    how="left"
)

# Unir ranking semántico con información completa de los CVs
df_ranking_final = df_ranking.merge(
    df_info_cvs[
        [
            "id",
            "experiencia_anios",
            "alineacion_esperada",
            "resumen_profesional",
            "experiencia_laboral",
            "habilidades_tecnicas",
            "habilidades_blandas",
            "certificaciones",
            "proyectos_relevantes"
        ]
    ],
    on="id",
    how="left"
)

# Esta función asigna un puntaje según los años de experiencia del candidato.
def puntaje_experiencia(anios):
    if anios >= 8:
        return 100
    elif anios >= 6:
        return 90
    elif anios >= 4:
        return 75
    elif anios >= 2:
        return 50
    else:
        return 30


# Esta función asigna un puntaje según el nivel profesional del candidato.
def puntaje_nivel(nivel):
    if nivel == "Senior":
        return 100
    elif nivel == "Intermedio":
        return 75
    else:
        return 40

def contiene(texto, palabras):
    texto = texto.lower()
    return any(palabra.lower() in texto for palabra in palabras)

# Esta función calcula un puntaje técnico para cada candidato.
def puntaje_tecnico(fila):
    texto = " ".join([
        str(fila["resumen_profesional"]),
        str(fila["experiencia_laboral"]),
        str(fila["habilidades_tecnicas"]),
        str(fila["habilidades_blandas"]),
        str(fila["certificaciones"]),
        str(fila["proyectos_relevantes"])
    ]).lower()

    puntaje = 0

    # Competencias de machine learning.
    if contiene(texto, ["machine learning", "ml", "modelos", "predictivo", "clasificación"]):
        puntaje += 15

    # Competencias de MLOps y ciclo de vida de modelos.
    if contiene(texto, ["mlops", "mlflow", "kubeflow", "monitoreo", "reentrenamiento", "versionar", "desplegar", "despliegue", "desplegado"]):
        puntaje += 15

    # Experiencia en nube.
    if contiene(texto, ["aws", "azure", "google cloud", "gcp", "cloud"]):
        puntaje += 12

    # Sistemas distribuidos y procesamiento a gran escala.
    if contiene(texto, ["spark", "kafka", "sistemas distribuidos", "distribuido", "databricks"]):
        puntaje += 12

    # Construcción de pipelines de datos.
    if contiene(texto, ["pipeline", "pipelines", "etl", "airflow", "feature store"]):
        puntaje += 12

    # Uso de frameworks de machine learning.
    if contiene(texto, ["pytorch", "tensorflow", "scikit-learn", "xgboost"]):
        puntaje += 10

    # Prácticas de integración y despliegue continuo.
    if contiene(texto, ["ci/cd", "github actions", "pruebas automatizadas", "despliegue continuo"]):
        puntaje += 10

    # Responsible AI, explainability y gobernanza de modelos.
    if contiene(texto, ["responsible ai", "explainable ai", "gobernanza", "explicable"]):
        puntaje += 7

    # Liderazgo técnico y arquitectura.
    if contiene(texto, ["liderazgo", "mentoría", "lead", "arquitectura", "stakeholders"]):
        puntaje += 7

    # Se devuelve el puntaje técnico total del candidato.
    return puntaje

# Se calcula el puntaje por años de experiencia.
df_ranking_final["puntaje_experiencia"] = df_ranking_final["experiencia_anios"].apply(puntaje_experiencia)

# Se calcula el puntaje por nivel profesional.
df_ranking_final["puntaje_nivel"] = df_ranking_final["nivel"].apply(puntaje_nivel)

# Se calcula el puntaje técnico a partir del contenido textual de cada CV.
df_ranking_final["puntaje_tecnico"] = df_ranking_final.apply(puntaje_tecnico, axis=1)

# Se calcula el puntaje final ponderado.
df_ranking_final["puntaje_final"] = (
    df_ranking_final["similitud_porcentaje"] * 0.40 +
    df_ranking_final["puntaje_experiencia"] * 0.20 +
    df_ranking_final["puntaje_nivel"] * 0.15 +
    df_ranking_final["puntaje_tecnico"] * 0.25
).round(2)

# Se ordenan los candidatos de mayor a menor puntaje final.
df_ranking_final = df_ranking_final.sort_values(
    "puntaje_final",
    ascending=False
).reset_index(drop=True)


# Se muestra el Top 10 del ranking final ponderado.
df_ranking_final[
    [
        "id",
        "perfil",
        "nivel",
        "formato",
        "similitud_porcentaje",
        "puntaje_experiencia",
        "puntaje_nivel",
        "puntaje_tecnico",
        "puntaje_final"
    ]
].head(10).style.format({
    "similitud_porcentaje": "{:.2f}",
    "puntaje_final": "{:.2f}"
})

In [118]:
# Se seleccionan los primeros 5 candidatos del ranking final ponderado.
top5_final = df_ranking_final.head(5).copy()

# Se muestra el Top 5 final con las columnas principales.
top5_final[
    [
        "id",
        "perfil",
        "nivel",
        "formato",
        "similitud_porcentaje",
        "puntaje_final"
    ]
].style.format({
    "similitud_porcentaje": "{:.2f}",
    "puntaje_final": "{:.2f}"
})

## 7.5 Justificación técnica del Top 5 final

Después de aplicar el ranking final ponderado, el sistema recomienda los siguientes cinco candidatos para la vacante de Lead Machine Learning Engineer. La selección combina similitud semántica con la vacante, años de experiencia, nivel profesional y cumplimiento de criterios técnicos como machine learning, MLOps, cloud computing, pipelines de datos, sistemas distribuidos, CI/CD, frameworks de ML, responsible AI y liderazgo técnico.

| Posición | Candidato | Perfil                         | Justificación                                                                                                                                                                                                                                                                                                             |
| -------: | --------- | ------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|        1 | CAND-016  | Lead Machine Learning Engineer | Es el candidato más sólido para la vacante. Tiene perfil senior, 8 años de experiencia y una alineación directa con el puesto. Su CV incluye machine learning, MLOps, arquitectura cloud, sistemas distribuidos, PyTorch, TensorFlow, Spark, MLflow, Kubernetes, AWS, CI/CD, monitoreo de modelos y liderazgo técnico.    |
|        2 | CAND-012  | Machine Learning Engineer      | Aunque es un perfil intermedio, tiene alta similitud semántica con la vacante y experiencia relevante en modelos productivos, pipelines de entrenamiento, despliegue cloud, PyTorch, TensorFlow, scikit-learn, MLflow, Docker, AWS y CI/CD. Es un candidato fuerte, aunque con menor seniority que CAND-016.              |
|        3 | CAND-017  | MLOps Engineer                 | Perfil senior muy relevante por su experiencia en MLOps, automatización, monitoreo, CI/CD, gobernanza, versionamiento, despliegue de modelos, Kubernetes, MLflow, Kubeflow, AWS y Terraform. Su fortaleza principal está en la operación productiva de modelos de machine learning.                                       |
|        4 | CAND-018  | Data Architect                 | Perfil senior con alta experiencia en soluciones intensivas en datos, cloud, sistemas distribuidos, Spark, AWS, Databricks, Airflow, Kafka y arquitectura de datos. Aunque no es estrictamente Machine Learning Engineer, aporta una base técnica muy fuerte para pipelines y plataformas de datos que alimentan modelos. |
|        5 | CAND-019  | Data Scientist                 | Perfil senior con experiencia en modelado predictivo, modelos de riesgo, explainable AI, scikit-learn, PyTorch, XGBoost, MLflow y monitoreo de desempeño. Su perfil es relevante para la parte analítica y de modelado, aunque menos orientado a infraestructura productiva que CAND-016 o CAND-017.                      |

El resultado final muestra que el sistema favorece perfiles con mayor correspondencia técnica y experiencia profesional. A diferencia del ranking semántico inicial, el ranking ponderado reduce el riesgo de seleccionar candidatos solo por coincidencia de vocabulario y permite una evaluación más adecuada para una vacante de nivel Lead.

In [119]:
# Se construye una lista de justificaciones para explicar por qué cada candidato fue incluido en el Top 5 final.
justificaciones_top5 = [
    {
        "posicion": 1,
        "id": "CAND-016",
        "perfil": "Lead Machine Learning Engineer",
        "justificacion": "Perfil senior con 8 años de experiencia, alta alineación con la vacante, experiencia en ML, MLOps, cloud, sistemas distribuidos, CI/CD, monitoreo de modelos y liderazgo técnico."
    },
    {
        "posicion": 2,
        "id": "CAND-012",
        "perfil": "Machine Learning Engineer",
        "justificacion": "Perfil intermedio con alta similitud semántica y experiencia en modelos productivos, pipelines de entrenamiento, PyTorch, TensorFlow, MLflow, Docker, AWS y CI/CD."
    },
    {
        "posicion": 3,
        "id": "CAND-017",
        "perfil": "MLOps Engineer",
        "justificacion": "Perfil senior especializado en MLOps, automatización, monitoreo, versionamiento, gobernanza, despliegue de modelos, Kubernetes, MLflow, Kubeflow, AWS y Terraform."
    },
    {
        "posicion": 4,
        "id": "CAND-018",
        "perfil": "Data Architect",
        "justificacion": "Perfil senior con experiencia en arquitectura de datos, cloud, sistemas distribuidos, Spark, AWS, Databricks, Airflow, Kafka y pipelines para modelos de machine learning."
    },
    {
        "posicion": 5,
        "id": "CAND-019",
        "perfil": "Data Scientist",
        "justificacion": "Perfil senior con experiencia en modelos predictivos, modelos de riesgo, explainable AI, scikit-learn, PyTorch, XGBoost, MLflow y monitoreo de desempeño."
    }
]

# Se convierte la lista de justificaciones en un DataFrame.
df_justificaciones_top5 = pd.DataFrame(justificaciones_top5)

# Se revisa que las justificaciones correspondan con los candidatos seleccionados en el Top 5 final.
ids_top5 = top5_final["id"].tolist()
ids_justificados = df_justificaciones_top5["id"].tolist()

if ids_top5 == ids_justificados:
    print("Las justificaciones coinciden con el Top 5 final.")
else:
    print("Revisar: las justificaciones no coinciden exactamente con el Top 5 final.")


# Se muestra la tabla de justificaciones del Top 5.
df_justificaciones_top5

Las justificaciones coinciden con el Top 5 final.

,posicion,id,perfil,justificacion
0,1,CAND-016,Lead Machine Learning Engineer,"Perfil senior con 8 años de experiencia, alta ..."
1,2,CAND-012,Machine Learning Engineer,Perfil intermedio con alta similitud semántica...
2,3,CAND-017,MLOps Engineer,"Perfil senior especializado en MLOps, automati..."
3,4,CAND-018,Data Architect,Perfil senior con experiencia en arquitectura ...
4,5,CAND-019,Data Scientist,Perfil senior con experiencia en modelos predi...

# 8. Reporte técnico y evaluación del sistema

## 8.1 Arquitectura implementada

El sistema desarrollado sigue una arquitectura multimodal de recuperación y ranking de candidatos. La entrada está compuesta por 20 CVs sintéticos almacenados en formatos PDF y PNG. Los documentos se procesan para extraer su contenido textual y posteriormente se representan mediante embeddings semánticos. La vacante seleccionada también se transforma en una consulta semántica, construida a partir de la descripción sintética del puesto y sus competencias clave.

La arquitectura general del sistema puede resumirse de la siguiente manera:

| Componente                 | Función                                                                                 |
| -------------------------- | --------------------------------------------------------------------------------------- |
| Vacante seleccionada       | Define los requisitos técnicos y profesionales contra los cuales se comparan los CVs.   |
| Base de CVs sintéticos     | Contiene 20 documentos anónimos con distintos niveles de experiencia y tipos de perfil. |
| Extracción de texto PDF    | Recupera el contenido textual de los CVs guardados como documentos PDF.                 |
| Extracción de texto PNG    | Recupera el contenido textual de los CVs guardados como imagen mediante OCR.            |
| Base textual de candidatos | Integra el contenido extraído de todos los CVs en una estructura tabular.               |
| Modelo de embeddings       | Convierte la vacante y los CVs en vectores semánticos comparables.                      |
| Búsqueda semántica         | Calcula la similitud entre la vacante y cada CV mediante similitud coseno.              |
| Ranking ponderado          | Combina similitud semántica, experiencia, nivel profesional y criterios técnicos.       |
| Top 5 final                | Propone los cinco candidatos más adecuados para la vacante con justificación técnica.   |

La solución no se limita a buscar palabras exactas. El uso de embeddings permite comparar el significado general de la vacante con el contenido de cada CV. Posteriormente, el ranking ponderado corrige posibles limitaciones de la búsqueda semántica, incorporando criterios técnicos necesarios para una vacante de nivel Lead.

## 8.2 Comportamiento observado de la solución

El sistema logró procesar correctamente los 20 documentos generados. La extracción de texto funcionó tanto para archivos PDF como para archivos PNG, lo cual confirma que la base de conocimiento multimodal pudo ser leída por el sistema.

En el ranking semántico inicial, los candidatos con mayor similitud fueron principalmente perfiles de Machine Learning Engineer, lo cual indica que el modelo de embeddings identificó adecuadamente términos y conceptos cercanos a la vacante. Sin embargo, también se observó una limitación: algunos perfiles Junior podían aparecer en posiciones altas debido a coincidencias semánticas, aunque no tuvieran la experiencia suficiente para una posición Lead.

Por esta razón, se implementó un ranking final ponderado. Este ranking integró la similitud semántica con criterios técnicos adicionales: años de experiencia, nivel profesional, MLOps, cloud computing, pipelines de datos, sistemas distribuidos, frameworks de machine learning, CI/CD, responsible AI y liderazgo técnico.

El resultado final fue más coherente con la vacante. El Top 5 quedó integrado principalmente por perfiles Senior y altamente relacionados con sistemas de machine learning en producción. El primer lugar fue ocupado por CAND-016, un perfil Lead Machine Learning Engineer Senior, seguido por perfiles de Machine Learning Engineering, MLOps, arquitectura de datos y ciencia de datos senior.

## 8.3 Evaluación técnica del desempeño

Desde una perspectiva técnica, el sistema tuvo un desempeño adecuado porque logró recuperar candidatos altamente alineados con la vacante y reducir el peso de perfiles que solo tenían coincidencia textual superficial. El ranking final muestra una mejor correspondencia con los requisitos reales del puesto, especialmente en experiencia, seniority, operación de modelos en producción y capacidades de arquitectura.

La solución también muestra un comportamiento razonable frente a perfiles parcialmente relacionados. Por ejemplo, perfiles como Data Architect o Data Scientist Senior aparecen en el Top 5 porque aportan capacidades relevantes para la vacante, aunque no sean equivalentes exactos a Machine Learning Engineer. En cambio, perfiles Junior o de Business Intelligence quedaron fuera del Top 5 final, lo cual es consistente con una vacante de nivel Lead.

En términos generales, el sistema cumple con el objetivo de apoyar la selección inicial de candidatos. No reemplaza el juicio humano, pero permite priorizar perfiles de manera trazable, justificar las recomendaciones y reducir el esfuerzo manual de revisión.

In [120]:
# Evaluación del desempeño del sistema

df_eval = df_ranking_final.copy()

# Se consideran relevantes los perfiles cuya alineación esperada era Alta o Muy alta
df_eval["es_relevante_experto"] = df_eval["alineacion_esperada"].isin(["Alta", "Muy alta"])

# Se seleccionan los primeros 5 candidatos del ranking final.
top5_eval = df_eval.head(5).copy()

# Se valida que el Top 5 contenga exactamente cinco candidatos.
assert len(top5_eval) == 5, "El Top 5 debe contener exactamente 5 candidatos."

# Se valida que existan perfiles relevantes para poder calcular Recall@5.
assert df_eval["es_relevante_experto"].sum() > 0, "Debe existir al menos un perfil relevante."

# Se valida que existan perfiles con alineación Muy alta para calcular su recuperación.
assert (df_eval["alineacion_esperada"] == "Muy alta").sum() > 0, "Debe existir al menos un perfil con alineación Muy alta."

precision_at_5 = top5_eval["es_relevante_experto"].mean()
recall_at_5 = top5_eval["es_relevante_experto"].sum() / df_eval["es_relevante_experto"].sum()
porcentaje_senior_top5 = (top5_eval["nivel"] == "Senior").mean()

total_muy_alta = (df_eval["alineacion_esperada"] == "Muy alta").sum()
muy_alta_en_top5 = (top5_eval["alineacion_esperada"] == "Muy alta").sum()
recuperacion_muy_alta = muy_alta_en_top5 / total_muy_alta


# Se agrupan las métricas calculadas en un diccionario.
metricas_evaluacion = {
    "Precision@5": round(precision_at_5, 2),
    "Recall@5": round(recall_at_5, 2),
    "Porcentaje Senior en Top 5": round(porcentaje_senior_top5, 2),
    "Recuperación de perfiles Muy alta": round(recuperacion_muy_alta, 2)
}

# Se convierte el diccionario de métricas en un DataFrame
df_metricas = pd.DataFrame(
    metricas_evaluacion.items(),
    columns=["Métrica", "Valor"]
)

# Se muestra la tabla final de métricas de evaluación.
df_metricas

                             Métrica  Valor
0                        Precision@5   1.00
1                           Recall@5   0.62
2         Porcentaje Senior en Top 5   0.80
3  Recuperación de perfiles Muy alta   1.00

## 8.4 Interpretación de las métricas

Las métricas obtenidas muestran un desempeño adecuado del sistema para una primera etapa de selección de talento. La métrica Precision@5 fue de 1.00, lo que significa que los cinco candidatos recomendados en el Top 5 fueron considerados relevantes de acuerdo con la alineación esperada definida previamente. Esto indica que el sistema logró priorizar perfiles técnicamente adecuados para la vacante.

La métrica Recall@5 fue de 0.62. Esto significa que el sistema recuperó dentro de las primeras cinco posiciones una parte importante de todos los candidatos considerados relevantes. Aunque no todos los perfiles con alineación Alta o Muy alta aparecen en el Top 5, el sistema sí logró recuperar a los candidatos más fuertes para una vacante de nivel Lead.

El porcentaje de perfiles Senior dentro del Top 5 fue de 0.80, es decir, cuatro de los cinco candidatos recomendados son Senior. Este resultado es coherente con la naturaleza de la vacante seleccionada, ya que el puesto de Lead Machine Learning Engineer requiere experiencia avanzada, liderazgo técnico y capacidad para trabajar con modelos de machine learning en producción.

Finalmente, la recuperación de perfiles con alineación Muy alta fue de 1.00. Esto indica que el sistema identificó correctamente a todos los candidatos previamente definidos como los más alineados con la vacante. Este resultado es especialmente importante porque muestra que el ranking final ponderado corrigió las limitaciones del ranking semántico inicial, evitando depender únicamente de coincidencias de vocabulario.

En conjunto, estas métricas sugieren que la solución funciona de manera razonable como herramienta de apoyo para la revisión inicial de candidatos. El sistema no reemplaza el juicio de un reclutador o experto técnico, pero sí permite priorizar perfiles, justificar recomendaciones y reducir el esfuerzo manual de revisión.

# 9. Ideas adicionales para medir el desempeño del sistema

Además de las métricas utilizadas en la evaluación anterior, el desempeño del sistema podría medirse mediante otros criterios cuantitativos y cualitativos. Estas métricas permitirían evaluar con mayor profundidad si el sistema recupera candidatos adecuados, si el ranking es consistente, si las recomendaciones son explicables y si existen posibles sesgos en el proceso de selección.

| Métrica o criterio                | Descripción                                                                                                                                                                               |
| --------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Precision@K                       | Permite medir qué proporción de los primeros K candidatos recomendados son realmente relevantes según un evaluador experto. Por ejemplo, Precision@3 o Precision@10.                      |
| Recall@K                          | Permite medir qué proporción de todos los candidatos relevantes fue recuperada dentro de las primeras K posiciones del ranking.                                                           |
| NDCG                              | Evalúa no solo si los candidatos relevantes aparecen en el ranking, sino también si aparecen en las posiciones correctas. Es útil cuando algunos candidatos son más relevantes que otros. |
| MRR                               | Mide qué tan pronto aparece el primer candidato altamente relevante dentro del ranking. Sería útil si el sistema se usa para reducir rápidamente la carga de revisión.                    |
| Comparación contra juicio experto | Un reclutador técnico o especialista en machine learning podría ordenar manualmente los candidatos y comparar ese orden contra el ranking generado por el sistema.                        |
| Evaluación de explicabilidad      | Se podría revisar si las justificaciones generadas por el sistema son claras, coherentes y basadas en evidencia presente en los CVs.                                                      |
| Auditoría de sesgos               | Se podría analizar si el sistema favorece o penaliza indebidamente ciertos perfiles, niveles de experiencia, tipos de formación o trayectorias profesionales.                             |
| Robustez ante formatos            | Se podría medir si el desempeño cambia entre CVs en PDF y CVs en PNG, especialmente considerando posibles errores de OCR en documentos de imagen.                                         |
| Cobertura de requisitos           | Se podría evaluar cuántos requisitos clave de la vacante aparecen cubiertos por cada candidato recomendado.                                                                               |
| Validación humana posterior       | Se podría analizar si los candidatos recomendados por el sistema también serían seleccionados por un equipo humano en una etapa posterior de revisión.                                    |

Estas mediciones permitirían fortalecer el sistema en una versión futura. En particular, sería importante combinar métricas automáticas con revisión humana, ya que la selección de talento no depende únicamente de similitud textual o coincidencia técnica. También intervienen factores como trayectoria, contexto profesional, capacidad de colaboración, comunicación, liderazgo, adaptación al equipo y potencial de crecimiento.

Una evaluación más completa debería considerar tanto la calidad del ranking como la calidad de las explicaciones. Un buen sistema de apoyo al reclutamiento no solo debe proponer candidatos adecuados, sino también justificar de forma clara por qué los recomienda. De esta manera, el sistema puede ser utilizado como una herramienta transparente, auditable y complementaria al juicio humano.

# 10. Comentarios y conclusiones finales

En esta actividad se desarrolló un sistema inteligente para apoyar la búsqueda y selección inicial de talento a partir de una vacante real. El proceso inició con la selección de una vacante de Lead Machine Learning Engineer publicada en el portal oficial de Capital One. A partir de esa vacante se identificaron los requisitos técnicos, responsabilidades, competencias clave y características esperadas del perfil ideal.

Posteriormente, se diseñó una base de 20 CVs sintéticos distribuidos en tres niveles de experiencia: Junior, Intermedio/Semi-Senior y Senior. Esta base incluyó perfiles variados, como Machine Learning Engineer, Data Scientist, Data Engineer, MLOps Engineer, BI Analyst y Software Engineer. La diversidad de perfiles permitió probar si el sistema era capaz de distinguir entre candidatos altamente alineados con la vacante, candidatos parcialmente relacionados y candidatos menos adecuados.

Un aspecto importante de la actividad fue la anonimización de los CVs. Para evitar sesgos y proteger la privacidad, los candidatos fueron identificados únicamente mediante códigos anónimos. No se incluyeron nombres, fotografías, género, edad, nacionalidad, estado civil, dirección, teléfono ni correo electrónico real. De esta forma, el sistema se concentró en información profesional relevante, como experiencia, habilidades técnicas, certificaciones, idiomas y proyectos.

La base de conocimiento se construyó de manera multimodal, utilizando documentos en formato PDF y PNG. Esto permitió probar la extracción de texto tanto desde documentos digitales como desde imágenes mediante OCR. Posteriormente, el contenido textual de los CVs fue convertido en embeddings semánticos para compararlo contra la descripción de la vacante.

El ranking semántico inicial permitió identificar perfiles cercanos a la vacante, especialmente candidatos con experiencia en Machine Learning Engineering. Sin embargo, también mostró una limitación importante: algunos perfiles podían aparecer en posiciones altas por coincidencia de vocabulario, aunque no cumplieran plenamente con el nivel de experiencia requerido para un puesto Lead. Por esta razón, se incorporó un ranking final ponderado que combinó similitud semántica con experiencia, nivel profesional y criterios técnicos.

El Top 5 final fue más coherente con la vacante seleccionada. Los candidatos recomendados incluyeron perfiles senior o altamente especializados en Machine Learning Engineering, MLOps, arquitectura de datos y ciencia de datos. Las métricas de evaluación también fueron favorables: Precision@5 fue de 1.00, Recall@5 fue de 0.62, el porcentaje de perfiles Senior en el Top 5 fue de 0.80 y la recuperación de perfiles con alineación Muy alta fue de 1.00.

En conclusión, el sistema cumplió con el objetivo de apoyar la selección inicial de candidatos mediante técnicas de Procesamiento de Lenguaje Natural. La solución permitió construir una base de conocimiento, extraer información desde documentos PDF y PNG, generar representaciones vectoriales, realizar búsqueda semántica, ordenar candidatos y justificar las recomendaciones finales.

A pesar de estos resultados, el sistema debe entenderse como una herramienta de apoyo y no como un reemplazo del juicio humano. En un contexto real, sería necesario validar las recomendaciones con reclutadores, especialistas técnicos y criterios adicionales de evaluación. También sería importante auditar posibles sesgos, mejorar la explicabilidad del ranking, ampliar la base de CVs y comparar los resultados contra decisiones humanas.

La actividad permitió observar que los sistemas de búsqueda semántica pueden ser útiles para reducir la carga inicial de revisión de perfiles, pero también mostró que la similitud textual no es suficiente por sí sola. Para obtener recomendaciones más robustas, es necesario combinar modelos semánticos con criterios técnicos, reglas de evaluación, supervisión humana y principios éticos de uso responsable de la inteligencia artificial.

# **Fin de la actividad : Búsqueda Inteligente de Talento**